alma/includes/CartData.php
alma/includes/PaymentData.php

Send cart contents upon payment creation to:
- Enable a better UX on our payment page (showing the cart content to the customer on our payment page should be a good reassurance)
- Help fraud detection

Cart contents

---

alma/lib/Model/CartData.php

Fix : Exclude non "default categories" from alma

fix: exclude non default category from alma payment

---

alma/lib/Utils/Settings.php

When I exclude categories, I get an error because `Settings::getExcludedCategories()` returns an object instead of an array

cast to array to fix warning if object

---

alma/alma.php
alma/controllers/hook/DisplayPaymentHookController.php
alma/controllers/hook/DisplayPaymentReturnHookController.php
alma/controllers/hook/DisplayProductPriceBlockHookController.php
alma/controllers/hook/DisplayShoppingCartFooterHookController.php
alma/controllers/hook/FrontHeaderHookController.php
alma/controllers/hook/PaymentOptionsHookController.php

for Alma pay store we needed a way to override some of the hook controller.
unfortunatly hookcontroller are not real prestahop controller, so using the prestashop override mecanism unless.
We added some code in alma.php to allow this mecanism to work with hook controllers.
we also removed the final key word from some class, to allow us to implements them

feat: added override option (prestashop like) for hook controllers

---

alma/lib/Utils/Settings.php

There was an error with lib Encryption if apikey was null. We can't send null of false to PhpEncryption->decrypt()
I had return false if apikey is null
Reset the module and got to configuration

error encryption if apikey is null

---

.github/workflows/e2e-test.yaml

Part of https://linear.app/almapay/issue/DEX-59/replace-infra-workflow-trigger-token-token-by-a-github-app
We want to replace all occurrences of this token, that is revoked every 3 months, by a Github App

[DEX-59] Replace infrastructure token by a Github app

---

CHANGELOG.md
alma/alma.php
alma/lib/Model/HookHelper.php

Fix issue with merchant where hooks aren't well hooked. Now we don't use the version of CMS but if the hook exist.
Add HookHelper to make the intelligents of the good hooks to hooked 
Install and/or reset the module to see if the goods are well hooked

Fix: To attach alma hook if hook exist

---

alma/lib/Helpers/ApiHelper.php
alma/upgrade/upgrade-3.0.0.php

[Activate inpage v2 automatically](https://linear.app/almapay/issue/MPP-506/activate-in-page-v2-automatically-if-in-page-v1-was-activated)
Migration to 3.0.0 to activate automatically the inpage v2 if inpage v1 is activated
Installe old version of our module 2.11.2 with inpage v1, activate inpage and update the module in 3.0.0 and check if inpage is always activated

Feat/mpp 506/activate in page v2 automatically if in page v1 was activated

---

alma/lib/Model/PaymentData.php

[Return to the payment step after cancel in Prestashop 1.6](https://linear.app/almapay/issue/MPP-519/return-in-payment-step-in-prestashop-16-on-cancel-payment)
We add the step 3 for step payment in the return url for cancel
Make a payment and clic Exit in Checkout Alma to see if we return in the payment page in Prestashop 1.6

feat MPP-519 Return in payment step in prestashop 1.6 on cancel payment

---

alma/views/templates/hook/_partials/displayPayment_deferred.tpl
alma/views/templates/hook/_partials/displayPayment_pnx.tpl
alma/views/templates/hook/payment_button_deferred.tpl
alma/views/templates/hook/payment_button_pnx.tpl

[Add escape for validation Prestashop](https://linear.app/almapay/issue/MPP-521/fix-prestashop-declined-publication-module)
add `|escape:'htmlall':'UTF-8'` in template smarty

add escape html for validation Prestashop

---

CHANGELOG.md
alma/CHANGELOG.md
alma/alma.php
alma/lib/Traits/AjaxTrait.php

[issue inpage prestashop < 16.0.12](https://linear.app/almapay/issue/MPP-541/fix-prestashop-1531)
Remove json_encode in return because we json_encode before
Make payment In-Page in Prestashop before 16.0.12

Fix: Inpage for Prestashop version before 16.0.12

---

alma/lib/Helpers/HookHelper.php

Our module doesn't install in Prestashop 8.1.0
[Fix install Prestashop 8.1.0](https://linear.app/almapay/issue/MPP-567/fix-hook-case-sensitive-on-prestashop-810)
Remove Hook Header with `H` because this Prestashop version is not case-sensitive
Install our last module version in Prestashop 8.1.0

Fix hook case sensitive on Prestashop 8.1.0

---

CHANGELOG.md
alma/CHANGELOG.md
alma/exceptions/ActivationException.php

[Error bad call method l](https://linear.app/almapay/issue/MPP-593/fix-error-if-activationexception-executed)
fix syntaxe call method ->l
Use API_KEY with account can't create payment

fix call method l() ActivationException

---

CHANGELOG.md
alma/CHANGELOG.md
alma/views/templates/hook/_partials/refunds.tpl
alma/views/templates/hook/order_refund_bs3.tpl
alma/views/templates/hook/order_refund_ps15.tpl

[Clear the partial refund amount after a partial refund](https://linear.app/almapay/issue/MPP-589/clear-the-partial-refund-amount-after-a-partial-refund)
Add jquery code to clear value input after refund and add id amount in input amount on Prestashop 1.6
Make a partial refund and see if the value is cleaned

Clear the partial refund amount after a partial refund

---

alma/controllers/hook/GetContentHookController.php
alma/exceptions/ActivationException.php
alma/exceptions/WrongCredentialsException.php
alma/translations/en.php

If your account has one api_key not activated, we throw an error ever if the mode selected is the api_key validated
[Don't boucle of all api_key when you select one mode with api_key](https://linear.app/almapay/issue/MPP-597/dont-boucle-of-all-api-key-when-you-select-one-mode-with-api-key)
We check the getMerchant only for the mode selected
Use an account with sandbox validated and live not validated and enter the both api_key and select the sandbox mode

Don't boucle of all api_key when you select one mode with api_key

---

alma/alma.php
alma/controllers/admin/AdminAlmaInsurance.php
alma/controllers/hook/GetContentHookController.php
alma/lib/Helpers/Admin/InsuranceHelper.php
alma/lib/Helpers/Admin/TabsHelper.php
alma/lib/Helpers/ApiHelper.php
alma/lib/Helpers/ConstantsHelper.php
alma/lib/Helpers/SettingsHelper.php
alma/translations/en.php
alma/views/templates/admin/insurance.tpl

[Linear task](https://linear.app/almapay/issue/MPP-723/handle-the-insurance-feature-flag-from-alma)
- flag name : feature:cms:insurance
- Retrieve the feature flag in the API from the endpoint /me/extended-data
- Save the information it in the CMS Database in the field ALMA_ALLOW_INSURANCE
- Create the menu link + page to go to the insurance's configuration if the flag insurance is allowed
Change bool 1 or 0 in file alma/lib/Helpers/ApiHelper.php line 97 `$isAllowInsurance`
Check in Dashboard Prestashop if the Insurance menu displayed or disappear depending the flag
And click in the menu to see the temporary message

Handle feature flag insurance in BO

---

alma/CHANGELOG.md
alma/alma.php
alma/composer.json
alma/controllers/admin/AdminAlmaInsurance.php
alma/controllers/hook/GetContentHookController.php
alma/exceptions/WrongParamsException.php
alma/lib/Helpers/Admin/InsuranceHelper.php
alma/lib/Helpers/Admin/TabsHelper.php
alma/lib/Helpers/ApiHelper.php
alma/lib/Helpers/ConfigurationHelper.php
alma/lib/Helpers/ConstantsHelper.php
alma/lib/Helpers/SettingsHelper.php
alma/phpunit.ci.xml
alma/tests/Unit/Helper/InsuranceHelperTest.php
alma/views/css/admin/almaPage.css
alma/views/templates/admin/insurance.tpl

[Linear task](https://linear.app/almapay/issue/MPP-718/prestashop-use-mocked-iframe-to-test-to-integrate-config-in-bo)
- Retrieve data from the DB to send to the iframe [DOC](https://www.notion.so/almapay/CMS-Widgets-iFrame-s-integrations-11cf4ad1a969435a8ed61d58aadab7b3?pvs=4#e114f68b29cf4d6ba0e28a6311deaaa7)
- Send data to iframe to display form with values
- When the save button in the BO form is clicked, the iframe is called up and returns the data
- We register them in DB
- Display a KO or OK return message
- Activate Flag Insurance in your Merchant ID
- Configure the module Alma
- Show the new Insurance tab in the menu Alma
- Save and Change your new configuration in the BO widget Insurance

Use mocked iframe to test to integrate config in bo

---

alma/controllers/admin/AdminAlmaCategories.php
alma/controllers/admin/AdminAlmaConfig.php
alma/controllers/admin/AdminAlmaRefunds.php
alma/controllers/admin/AdminAlmaShareOfCheckout.php
alma/controllers/front/ipn.php
alma/controllers/front/payment.php
alma/controllers/front/validation.php
alma/exceptions/ActivationException.php
alma/exceptions/AlmaException.php
alma/exceptions/ApiMerchantsException.php
alma/exceptions/ClientException.php
alma/exceptions/MissingParameterException.php
alma/exceptions/PaymentNotFoundException.php
alma/exceptions/RefundException.php
alma/exceptions/RenderPaymentException.php
alma/exceptions/ShareOfCheckoutException.php
alma/exceptions/WrongCredentialsException.php
alma/lib/API/MismatchException.php
alma/lib/Helpers/ApiHelper.php
alma/lib/Helpers/CustomFieldsHelper.php
alma/lib/Helpers/EligibilityHelper.php
alma/lib/Helpers/SettingsCustomFieldsHelper.php
alma/lib/Hooks/FrontendHookController.php
alma/lib/Logger.php
alma/lib/Model/CartData.php
alma/lib/Model/PaymentData.php
alma/lib/Model/ShippingData.php
alma/lib/Validators/PaymentValidation.php
alma/lib/Validators/PaymentValidationError.php
alma/lib/smarty.php

[Linear task](https://linear.app/almapay/issue/MPP-838/validation-module-for-release-310)
To ensure that PHP files are executed in the PrestaShop context, you must add the following code to the start of all PHP files: if (!defined('_PS_VERSION_')) { exit; }
Make E2E Test

Validation module for release 3.1.0

---

CHANGELOG.md
alma/alma.php
alma/controllers/hook/PaymentOptionsHookController.php
alma/views/templates/hook/_partials/feePlan.tpl

[Linear task](https://linear.app/almapay/issue/MPP-903/🏃-p1x-tresors-dargan)
We don't display form for in page in Pay now Payment
Disable In-page and make a payment Pay now

hotfix: Pay now is broken if In-Page is disabled

---

alma/views/js/alma-product.js

Fixes MPP-991
This code hides the customization input 
- Hides the whole block if there is only our customization
- Hides only the input if there are other customization
Note : I'm not sure that selecting elements based on className is really stable, would it be broken for different themes ? I did not find a better way for now :(

(JS) : Hide customisation input

---

alma/views/js/alma-cart.js

[Linear task](https://linear.app/almapay/issue/MPP-1023/fix-display-cart-item-when-reload-cart)
Display the insurance item on cart page after change quantity and items are reloaded
Add product with insurance, then add product without insurance and change the quantity of the product without insurance.

Fix display cart item when reload cart

---

alma/alma.php
alma/controllers/hook/DisplayCartExtraProductActionsHookController.php
alma/controllers/hook/TermsAndConditionsHookController.php
alma/lib/Helpers/HookHelper.php
alma/translations/en.php
alma/translations/fr.php
alma/views/js/alma-inpage.js

[Linear task](https://linear.app/almapay/issue/MPP-868/opt-in-for-prestashop)
Add terms and conditions alma insurance on the checkout page 
Activate Alma Insurance and go head to the checkout page and see the new checkbox terms and conditions Alma Insurance

Opt in insurance for Prestashop

---

alma/controllers/hook/DisplayCartExtraProductActionsHookController.php
alma/lib/Helpers/ImageHelper.php
alma/views/templates/hook/_partials/cartProducts.tpl

[Linear task](https://linear.app/almapay/issue/MPP-1032/test-insurance-feature-with-other-template-prestashop)
We get the insurance image product with the method Prestashop getImageLink
We fix the item insurance in cart page for integration with bootstrap css
Install our module, enable Insurance option, Install the WareHouse theme
And try to buy an insurance

[insurance] Insurance feature with other theme prestashop

---

alma/controllers/hook/FrontHeaderHookController.php
alma/lib/Helpers/SettingsHelper.php

[Linear task](https://linear.app/almapay/issue/MPP-1033/explo-insurance-in-quick-view-speed-buy-in-the-modal)
Add asset insurance and the widget in the home page
And add selector css for price for the widget in the default configuration
Install the module and enable Insurance.
Go to the home page and click to the quick view on the product home page

[insurance] Explo insurance in quick view (speed buy) in the modal

---

alma/views/css/admin/almaPage.css

[Merchant issue](https://github.com/alma/alma-installments-prestashop/issues/241)
[Linear task](https://linear.app/almapay/issue/MPP-905/fix-display-notification-soc-in-module-page)
Add sublevel to selector the CSS notification block SOC
Install our module
Enable the live mode
Go to the Module Manager
And see the notification of Share of Checkout in the module manager page

[develop] Fix css notification SOC in module page

---

CHANGELOG.md
alma/alma.php
alma/views/css/alma.css
alma/views/js/alma-inpage.js
alma/views/templates/hook/_partials/displayPayment_deferred.tpl
alma/views/templates/hook/_partials/displayPayment_pnx.tpl

[Linear task](https://linear.app/almapay/issue/MPP-937/add-loader-on-payment-button-ps16-if-the-page-isnt-completely-loaded)
Add loader in payment button is page isn't completely loaded to display in-page correctly
https://components.storybook.alma.tech/?path=/story/components-button--button-primary
**For Prestashop 1.6**
1st Test
Install our module
Active the in-page option
Active slow 3G in network in console 
And display the payment button with in-page and try to click on it
2nd Test
Active the `one page checkout` in the Preferences > Orders > Order process type, Save
In the front end, make the order, before click to payment button, change the quantity product (with and without eligibility)
And check the loader button and click to pay with Alma and In-Page

[develop] Add loader on payment button ps16 if the page isn't completely loaded

---

CHANGELOG.md
alma/alma.php
alma/views/js/alma-inpage.js

[Linear task](https://linear.app/almapay/issue/MPP-1016/🏃-center-51-in-page)
Unmount and remove event for each payment button selector to fix if the modal isn't open before to change payment method
**For Prestashop 1.7**
Install our module
Activate In-Page option.
Select payment Alma with In-Page but don't click to Place Order !
And without open the modal, change the payment method and try to pay with the new payment method.

[develop] Hotfix/run center 51 in page

---

alma/lib/Repositories/CombinationRepository.php
alma/lib/Services/CombinationProductAttributeService.php
alma/lib/Services/InsuranceProductService.php

[Linear task](https://linear.app/almapay/issue/MPP-1142/fix-creation-combination-insurance-with-the-same-name)
Add price on verification if combination of insurance product existe if there are the same name but the different price
Add insurance product with the same name but different price

[insurance] Fix creation combination insurance with the same name

---

alma/views/js/alma-product-insurance.js

[Linear task](https://linear.app/almapay/issue/MPP-1147/fix-when-i-select-an-insurance-the-quantity-set-at-1)
Set quantity product if is changed when you select an insurance for set the same quantity in the product
Change the quantity then select an insurance and see if the quantity is the same

[insurance] Fix when i select an insurance the quantity set at 1

---

alma/controllers/hook/TermsAndConditionsHookController.php
alma/lib/Services/InsuranceService.php

[Linear task](https://linear.app/almapay/issue/MPP-1119/prestashop-improve-opt-in-wording-files-link)
Add document in the opt-in text of insurance
Buy an insurance and see the opt-in text before the payment

[insurance] Improve opt in wording files link

---

alma/views/js/alma-product-insurance.js

[Linear task](https://linear.app/almapay/issue/ECOM-1158/get-the-eligibility-info-if-the-product-havent-insurance-and-disabled)
Get the eligibility of the api in the widget to enable or not the event to click of insurance
- Add to cart a product with insurance Eligible
- Add to cart a product with insurance not Eligible and in the catalogue insurance
- Add to cart a product with insurance not in the catalogue insurance

[insurance] Get the eligibility info if the product havent insurance and disabled

---

CHANGELOG.md
alma/alma.php
alma/views/css/admin/almaPage.css

[Linear task](https://linear.app/almapay/issue/ECOM-1170/backoffice-almapagecss-breaks-switchs-in-prestashop-81)
Remove CSS to fix switch Prestashop 8
Up Prestashop 8.1+
Connect to the back office
Go to Shop parameters > Search
And the switch button if it's right

[main] Backoffice almaPage.css breaks switchs in Prestashop 8.1+

---

alma/views/js/alma-product-insurance.js

[Linear task](https://linear.app/almapay/issue/ECOM-1189/remove-input-insurance-in-dom-when-click-on-remove-insurance-in-the)
Identify if we remove the insurance via the widget and remove in the DOM the input insurance
Add an insurance with the widget 
then remove it with the button in the widget
and add to cart to see if the insurance isn't in the cart

Remove input insurance in DOM when click on remove insurance in the widget

---

alma/lib/Repositories/StockAvailableRepository.php
alma/lib/Services/CombinationProductAttributeService.php
alma/lib/Services/InsuranceProductService.php
alma/lib/Services/StockAvailableService.php

The insurance product stock is negative
[Linear task](https://linear.app/almapay/issue/ECOM-1162/make-sure-that-the-insurance-quantities-are-always-positive)
- Mount a clean PS infra
- Order insurances
- See if the amount of stock is correct in the BO insurance product page, combinations tab
- See if in the bo in the order , the field available is good and you don't have this message

Fix stock quantity on insurance product

---

alma/composer.json
alma/controllers/admin/AdminAlmaInsuranceOrders.php
alma/lib/Repositories/AlmaInsuranceProductRepository.php
alma/lib/Services/InsuranceProductService.php
alma/lib/Services/InsuranceService.php

[Linear task](https://linear.app/almapay/issue/ECOM-1208/change-contract-infos-storage-in-db)
- mount a new clean PS infra
- do insurance subscriptions
- in the admin alma/insurance/orders check if the fields insurance_contact_id and insurance_price are not empty or check in db that insurance_contract_id, cms_reference and product price are not empty for table ps_alma_insurance

Change DB structure for association page

---

alma/controllers/hook/DisplayProductActionsHookController.php
alma/lib/Helpers/CartHelper.php
alma/lib/Model/PaymentData.php
alma/lib/Services/InsuranceApiService.php
alma/views/js/alma-product-insurance.js

Add headers in Insurance API call subscription & eligibility
Send session ID and cart id as header to : 
- eligibility call made from CMS
- subscription call made from CMS
- widget iframe
[Linear task](https://linear.app/almapay/issue/ECOM-1198/prestashop)

Send session id and id cart 

---

CHANGELOG.md
alma/alma.php
alma/composer.json
alma/controllers/admin/AdminAlmaRefunds.php
alma/views/templates/hook/order_refund_bs3.tpl
alma/views/templates/hook/order_refund_bs4.tpl
alma/views/templates/hook/order_refund_ps15.tpl

[Linear task](https://linear.app/almapay/issue/ECOM-1262/%5Bmodule%5D-add-verification-type-number-on-field-amount)
Change inputs type to number and return an error if amount equals zero.
Make a partial refund with string, with decimal number and with zero.

Add verification type number on field amount

---

alma/controllers/hook/DisplayProductActionsHookController.php

[Linear task](https://linear.app/almapay/issue/ECOM-1286/send-cartid-and-customersessionid-to-the-iframe)
We add the customer session id and the cart id in the url of the insurance widget iframe
Display the insurance widget and see in the url if the cartId ans customerSessionId are displayed

[insurance] Send cartId & customerSessionId to the iFrame

---

alma/lib/smarty.php

Resolved an issue where the smarty library was incorrectly loaded during command-line executions. This fix prevents the library from being called in CLI context, aligning with the intended behavior of module operations in a non-web environment.

fix: ensure library is not invoked in CLI mode

---

alma/controllers/hook/DisplayPaymentHookController.php

[Linear task](https://linear.app/almapay/issue/ECOM-1256/bug-pay-now-not-working-ps-15-16-without-inpage)
We forced `true` on InPage for Pay Now on PS < 1.7
We replaced with the variable which is set in configuration
- Install the module
- disabled In Page
- Go to the payment page and pay with Pay now

[develop] Bug : Pay Now not working PS 1.5 / 1.6 without inpage

---

alma/composer.json
alma/controllers/admin/AdminAlmaInsuranceOrders.php
alma/lib/Helpers/ApiHelper.php
alma/lib/Model/InsuranceProduct.php
alma/lib/Repositories/AlmaInsuranceProductRepository.php
alma/lib/Services/InsuranceSubscriptionService.php

Change format data
[Linear task](https://linear.app/almapay/issue/ECOM-1278/prestashop)
add cancellation url to subscription #292
[Linear task](https://linear.app/almapay/issue/ECOM-1220/prestashop-sends-the-key-cancel-url-with-the-subscription)
http://prestashop-a-1-7-8-7.local.test/module/alma/subscription?action=update&sid=test&trace=test
response : {"success":true}
http://prestashop-a-1-7-8-7.local.test/module/alma/subscription?action=update&trace=test
response : {"error":"Missing id"}
http://prestashop-a-1-7-8-7.local.test/module/alma/subscription?action=update&sid=test
response : {"error":"Missing security token"}
http://prestashop-a-1-7-8-7.local.test/module/alma/subscription?sid=eeeeee&trace=eeee
response : {"error":"Wrong action"}

[insurance] change fields from insurance association table + add cancellation url to subscription

---

alma/controllers/hook/StateHookController.php
alma/lib/Helpers/InsuranceHelper.php
alma/lib/Model/InsuranceProduct.php
alma/lib/Repositories/AlmaInsuranceProductRepository.php
alma/lib/Services/InsuranceSubscriptionService.php

Prevent to recreate a subscription on status order changed
[Linear task](https://linear.app/almapay/issue/ECOM-1319/prevent-ps-to-recreate-subscription-on-status-order-change)
- create multiple orders with subscriptions
- change the status of order on for exemple backorder payed, then in Payment accepted and check that the subscription stored has not changed of subscription id or broker
- go to the db and set to null the subscription_state and subscription_broker of an order, change the status of order on for exemple backorder payed, then in Payment accepted and check that the subscription stored  has now a broker and a state

Prevent to recreate subscription on status order change

---

.github/workflows/aqua.yml

To match repository's gitflow, we need to enable Aqua scans on PR targeting `develop`.
Modify `aqua.yml` workflow to trigger scan on PR targeting `develop`.
No test needed.
- [x ] The title of the PR uses business wording, not technical jargon, for the changelog readers to understand it

[Security] Enable vulnerability scanner on PR targeting develop

---

alma/lib/Services/InsuranceService.php
alma/lib/Services/InsuranceSubscriptionService.php

[Linear task](https://linear.app/almapay/issue/ECOM-1337/[prestashop]-add-amount-insurance-in-the-subscription-endpoint)
Add amount insurance in the subscription endpoint
Buy an insurance and see if there is the good price of insurance in the table alma_insurance_product

[insurance] Add amount insurance in the subscription endpoint

---

alma/controllers/hook/TermsAndConditionsHookController.php
alma/lib/Services/InsuranceService.php

[Linear task](https://linear.app/almapay/issue/ECOM-1340/[prestashop]-update-opt-in-copy)
Change wording Opt-in insurance
And remove name of insurance
Add an insurance product in your cart
Go to the checkout page for payment
See the wording of the opt-in insurance

[insurance] Update opt in (copy)

---

alma/controllers/hook/TermsAndConditionsHookController.php
alma/lib/Services/InsuranceService.php
alma/lib/Services/InsuranceSubscriptionService.php

[Linear task](https://linear.app/almapay/issue/ECOM-1355/[prestashop]-remove-broker-id-from-subscription-creation-response)
Remove broker_id from subscription creation response
Subscribe an insurance and we don't update the broker_id in the subscription insurance table

[insurance] remove broker_id from subscription creation response

---

alma/lib/Repositories/AlmaInsuranceProductRepository.php

[Linear task](https://linear.app/almapay/issue/ECOM-1375/[🧩-ps]-explo-error-log-duplicate-entry)
Remove constraint unique subscription_id and subscription_broker_id db
Buy two insurances and see if you have two subscription on pending and see the log if there is any error

[insurance] Explo error log duplicate entry

---

alma/alma.php
alma/controllers/hook/ActionOrderGridDefinitionModifierHookController.php
alma/controllers/hook/ActionOrderGridQueryBuilderModifierHookController.php
alma/lib/Helpers/HookHelper.php

[Linear task](https://linear.app/almapay/issue/ECOM-1307/[%F0%9F%A7%A9-ps]-add-column-in-order-list-view)
- do orders with insurance + go to the BO order page and see the new column
(need to reset the module to install the hook or have a new infra)

feat: add column has insurance in order view >= PS 1.7.7

---

alma/controllers/admin/AdminAlmaInsuranceOrders.php

[Linear task](https://linear.app/almapay/issue/ECOM-1437/[%F0%9F%A7%A9-ps]-fix-orders-page-insurance-back-office-before-we-finalise-the)
Go to the page order in front with insurance in your cart, ensure that the BO alma insurance order page is not broken

fix: order page is broken

---

alma/controllers/admin/AdminAlmaInsuranceOrdersDetails.php

[Linear task](https://linear.app/almapay/issue/ECOM-1489/[%F0%9F%A7%A9-ps]-reason-is-not-displayed-in-iframe)
Cancel a subscription with a reason, the reason must be visible

fix the display of reason of cancellation

---

alma/controllers/admin/AdminAlmaInsuranceOrdersDetails.php
alma/lib/Helpers/ConstantsHelper.php
alma/views/templates/admin/insurance_order_details.tpl

[Linear task](https://linear.app/almapay/issue/ECOM-1500/[🧩-ps]-add-dynamic-url-on-the-iframe-insurance-order-detail-for-the)
We replace static url of element insurance order detail in dynamic url for sandbox/prod env
Install module with insurance
Order an insurance with the basic process
See if the url of the iframe and modal js are link to the sandbox env

Add dynamic url on the iframe insurance order detail for the sandbox/prod env

---

alma/views/js/alma-product-insurance.js

[Linear task](https://linear.app/almapay/issue/ECOM-1594/[🧩-ps]-handle-quantity-with-insurance-for-ipnl-and-odp)
Selector quantity by input name and not the id
Add a insurance with a quantity if you change the id of input quantity_wanted

Fix handle quantity if input id isn't quantity_wanted

---

alma/views/js/alma-product-insurance.js
alma/views/templates/hook/displayAdminOrderTop.tpl

[Linear task](https://linear.app/almapay/issue/ECOM-1612/[🧩-ps]-fix-order-warning-ui)
Fix block row warning UI order page
Fix height insurance widget when iframe we return 45 (min size of widget)
Display de warning message in order page with insurance on fullscreen
Tested on ODP, display the widget on ODP website

Fix order warning UI

---

alma/views/js/admin/alma-insurance-orders.js
alma/views/templates/hook/DisplayBackOfficeHeader.tpl

[Linear task](https://linear.app/almapay/issue/ECOM-1624/[ps]-fix-change-order-state-in-the-orders-page-bo)
Change simple quote to double quote to handle translation FR on the wording for the modalConfirm on ordre page for insurance feature
Add your store in french
Order an insurance
Change the state of the order on a refund state

[insurance] Fix change order state in the orders page bo

---

alma/lib/Helpers/CartHelper.php
alma/lib/Services/InsuranceApiService.php
alma/tests/Unit/Helper/CartHelperTest.php
alma/tests/Unit/Helper/ConfigurationHelperTest.php
alma/tests/Unit/Helper/PlanHelperTest.php
alma/tests/Unit/Helper/ToolsHelperTest.php

[Linear task](https://linear.app/almapay/issue/ECOM-1653/[🧩-ps]-check-why-cart-id-is-not-sent-with-subscription-in-prod)
On the subscription we have the order. We send directly the cart_id from the order
Subscribe an insurance and check the attach rate data

Check why cart id is not sent with subscription in prod

---

alma/controllers/hook/GetContentHookController.php
alma/views/templates/hook/getContent.tpl

[Linear task](https://linear.app/almapay/issue/ECOM-1672/[%F0%9F%A7%A9-ps]-display-the-ps-link-in-the-configuration-form)
You see the prestashop account module on top of the alma conf form

render always ps account form

---

alma/alma.php
alma/composer.json
alma/controllers/hook/GetContentHookController.php
alma/views/templates/hook/getContent.tpl

[Linear task](https://linear.app/almapay/issue/ECOM-1673/[%F0%9F%A7%A9-ps]-handle-the-display-of-the-ps-link-only-if-the-module-ps)
On PS 1.6 you must have the suggest PS account module message, then when you install the module, you see the module

Handle ps account & PS 1.6

---

.pre-commit-config.yaml
Taskfile.yml
alma/alma.php
alma/config/admin/index.php
alma/config/index.php
alma/lib/Builders/Admin/index.php
alma/lib/Builders/index.php
alma/lib/Factories/index.php
alma/lib/Grid/Column/index.php
alma/lib/Grid/index.php
alma/lib/Helpers/Admin/index.php
alma/tests/Unit/Builders/Admin/index.php
alma/tests/Unit/Builders/index.php
alma/tests/Unit/Factories/index.php
alma/tests/Unit/Helper/Admin/index.php
alma/tests/Unit/Helper/index.php
alma/tests/Unit/Model/index.php
alma/tests/Unit/Services/index.php
alma/tests/Unit/index.php
alma/views/PrestaShop/Admin/Common/Grid/Columns/Content/index.php
alma/views/PrestaShop/Admin/Common/Grid/Columns/index.php
alma/views/PrestaShop/Admin/Common/Grid/index.php
alma/views/PrestaShop/Admin/Common/index.php
alma/views/PrestaShop/Admin/index.php
alma/views/PrestaShop/index.php
alma/views/js/admin/components/index.php
scripts/remove-blank-line-index.sh

Fixes issues encountered locally with linter : 
* `autoindex` was updating vendor, so `php-cs-fixer` was failing silently if running after `autoindex` (It was always passing)
* `scripts/remove-blank-line-index.sh` was only working on MAC
*  AND `scripts/remove-blank-line-index.sh` removes lines that are added by the lint:fix, so we never ends in a situation where both are satisfied
* The vendor folder is now excluded from autoindex 
*  We check the local OS in `scripts/remove-blank-line-index.sh` and execute the right sed command 
* BUT I finally commented the script as it is not coherent with the linter
* Lots of linting change

[devx] Fix local lint:fix

---

alma/controllers/hook/GetContentHookController.php
alma/lib/Helpers/ApiHelper.php
alma/views/templates/hook/getContent.tpl

=
[Linear task](https://linear.app/almapay/issue/ECOM-1690/[%F0%9F%A7%A9-ps]-merchant-installing-the-module-for-the-first-time)
When the alma module is already installed and configure, you see the connect PS link
If the alma module has no keys, you have not access to the alma form

PS account first alma activation

---

alma/alma.php

[Linear task](https://linear.app/almapay/issue/ECOM-1696/%5B%F0%9F%A7%A9-ps%5D-fix-in-dev-mode-ps-account-must-not-appear)
PS account does not appear in dev mode, and you can fill Alma form config

fix ps account in dev mode

---

.github/release-drafter.yml

We need a release draft template to implement the release workflow (See the part for the automated release PR creation : https://github.com/alma/alma-installments-prestashop/pull/405)
We cannot test this workflow if the template **is not merged in the default branch** (See https://github.com/release-drafter/release-drafter?tab=readme-ov-file#configuration)
This adds a minimal release draft template

[devx] Add a release draft template

---

.github/workflows/e2e-test.yaml

Will supersede https://github.com/alma/alma-installments-prestashop/pull/428.
`actions/create-github-app-token` is the Github-supported way to generate Github tokens for applications.

Replace 'tibdex/github-app-token' with 'actions/create-github-app-token'

---

alma/views/js/alma-product-insurance.js

[Linear task](https://linear.app/almapay/issue/ECOM-1726/[🧩-ps]-issue-about-the-quantity-when-selecting-insurance-with-more-1)
We check if the quantity is different between input and ProductDetail
If yes we get the quantity of input to set the quantity
We need to test on ODP because they haven't event to updateProduct when the quantity change

fix quantity issue with insurance without updateProduct event

---

alma/tests/Unit/Helper/PaymentOptionTemplateHelperTest.php

[Linear task](https://linear.app/almapay/issue/ECOM-1583/[%F0%9F%A7%A9-ps]-unit-paymentoptiontemplatehelpertest)
- Run the unit tests

add paymentoptiontemplatehelepr tests

---

.github/workflows/backport-pull-request.yml
.github/workflows/release-pull-request.yml

https://linear.app/almapay/issue/DEX-815/prestashop-create-develop-backport-github-workflow
This adds a new Github workflow that will be triggered when a pull request containing the label "release" is merged
This workflow will create a new pull request that updates the develop branch with the changes pushed on main for the release.
> [!WARNING]
> This has been tested on https://github.com/alma/github-actions-experiments
> It will have to be tested on this repository during the next release

[DEX-815] Add backport Github workflow

---

.github/workflows/release-publish.yml
.gitignore

https://linear.app/almapay/issue/DEX-814/prestashop-create-release-github-workflow
This adds a new Github workflow that will be triggered when a pull request containing the label "release" is merged : 
* It will fetch the current draft release, add the zip file and publish it
* It will send a Slack message to #alma_changelog with the content of the release 
> [!WARNING]
> This has only been tested on https://github.com/alma/github-actions-experiments
> It will have to be tested on this repository during the next release

[DEX-814] Add Github release workflow

---

.github/workflows/release-pull-request.yml
Taskfile.yml

https://linear.app/almapay/issue/DEX-809/prestashop-add-task-hotfix-command
https://linear.app/almapay/issue/DEX-863/prestashop-add-a-task-release-command-to-trigger-workflow-release-pull
This adds two task commands : 
* task release
* task hotfix
These 2 commands trigger the `release-pull-request` and `hotfix-pull-request` workflows respectively, that open a pull request for release/hotfix changes
These task commands require `gh` cli to be installed, and a Github personal token
Note that `hotfix-pull-request` workflow is not yet available, but will be with https://github.com/alma/alma-installments-prestashop/pull/445

[DEX-863][DEX-809] Add a task command to trigger release/hotfix workflow

---

.github/workflows/ci.yaml
.github/workflows/e2e-test.yaml
.github/workflows/hotfix-pull-request.yml

https://linear.app/almapay/issue/DEX-870/prestashop-add-hotfix-github-workflow
* This adds a new Github Workflow `hotfix-pull-request` that can be triggered manually 
This workflow requires a changelog message as an input
This workflow does following actions : 
* Creates a release draft (with a computed version number)
* Updates the release draft body with the changelog message provided as input
* Updates the CHANGELOG.md file with the same content
* Updates the files containing the version number using `./scripts/update-files-with-release-version.sh`
* Creates a branch hotfix/<release_tag_name> from `main` branch containing previous changes
* Opens a pull request base on main and labeled `hotfix`
* This updates `ci` and `e2e-test` workflows in order not to trigger unit tests and E2E …

[DEX-870] Add hotfix GitHub workflow

---

alma/alma.php

[Linear task](https://linear.app/almapay/issue/ECOM-1753/[🧩-ps]-hotfix-name-module-cant-use-constant)

fix name module can't use constant

---

.github/workflows/release-publish.yml

* The link to the new Github version in the Slack message was wrong (It was using the link to the draft version, which was an "untagged" version)
* I updated a little bit the content of the message so that it reflects what is currently sent for Prestashop releases

[DEVX] Fix release slack message

---

compose.yml

This avoids us having a root-owned folder in `alma/`.

[devx] Use a mysql docker volume instead of local folder

---

.pre-commit-config.yaml
cz.yaml

Add commit-message check to respect commitizen convention on pre-commit
How to test : 
- Install commit-msg hook `pre-commit install --hook-type commit-msg` 
- Make any change (like delete a work in the README.md)
- `git add`
- `git commit -m "wrong commit message"`
- pre-commit hook should block your commit as the commit message does not meet the commitizen convention, you should see
```
commit validation: failed!
please enter a commit message in the commitizen format.
commit "": "wrong commit message"
pattern: (?s)(build|ci|docs|feat|fix|perf|refactor|style|test|chore|revert|bump)(\(\S+\))?!?:( [^\n\r]+)((\n\n.*)|(\s*))?$
```
- Try a commit message that respects the convention, for example `git commit -m "test(pr): commit test for pr"`
- Your commit should be created correctly
- Do not …

Add commit message check

---

alma/lib/Model/PaymentData.php
alma/tests/Unit/Model/PaymentDataTest.php

[Linear task](https://linear.app/almapay/issue/ECOM-1784/[🧩-ps]-gather-cart-data-from-pnx-and-deferred-payments)
Juste delete the "if" condition which used to verify if the payment methods is > 5 to add cart data in the payment object.
And add some unit tests.
You can run unit tests.

Gather cart data from pnx and deferred payments

---

.github/renovate.json

@Benjamin-Freoua-Alma was not able to build the module anymore following this Renovate update: https://github.com/alma/alma-installments-prestashop/pull/425
@Benjamin-Freoua-Alma fixed the issue by reverting the composer version to 2.2 here: https://github.com/alma/alma-installments-prestashop/pull/479
We need to configure Renovate to stop updating this version
We disable updates of composer for the file `scripts/build/Dockerfile`
@gdraynz I tried something but I'm not sure if it's OK, wdyt ?

[DEVX][RENOVATE] Freeze composer version

---

.github/renovate.json

We want to avoid Renovate from pushing these updates : https://github.com/alma/alma-installments-prestashop/pull/429

[RENOVATE] Disable automatic PHP version update in Dockerfile

---

.github/renovate.json

We want to avoid Renovate from opening pull requests suggesting to update the prestashop version in Dockerfile
See this for example : https://github.com/alma/alma-installments-prestashop/pull/485
> [!WARNING]  
> Note that https://github.com/alma/alma-installments-prestashop/pull/480 was opened to prevent the composer update but I should have merged it on `main` rather than `develop` to take effect, so I apply the same change here, but it will probably cause conflicts when develop will be merged on main and/or the other way around, I apologize

[DEVX][RENOVATE] Disable auto update of Prestashop version in Dockerfile

---

.github/pr-labeler.yml
.github/release-drafter.yml
.github/workflows/backport-pull-request.yml
.github/workflows/pr-labeler.yml
.github/workflows/release-publish.yml
.github/workflows/release-pull-request.yml

(cherry picked from commit 24c32cc266df3b9aab031fc27a25db0594002569)
I want this change : https://github.com/alma/alma-installments-prestashop/pull/497 to also be merged on main so that it will be effective for the next release

[DEVX] Merge release-drafter update on main

---

.github/renovate.json
.github/workflows/release-publish.yml

* Ping EM and PM in the Slack release message
* v1.1.1 of `LoveToKnow/slackify-markdown-action` fixes the issue we had with v1.0.2 so it can be safely used
* Publish the release message to #alma_changelog

[DEVX] Update Slack release message

---

.github/workflows/ci.yaml
.pre-commit-config.yaml
Taskfile.yml

* Add ~~`task install:pre-commit`~~ `task pre-commit:install` as a new hook type has been introduced with https://github.com/alma/alma-installments-prestashop/pull/471 and needs to be installed explicitely 
* Fix the github workflow url displayed for `task release` and `task hotfix`
* Align with other repositories and use `task:test`
* `release` branch name needs to be allowed if we want to push changes on a release branch

[DEVX] Add a task to install pre-commits + small changes on tasks

---

alma/views/js/alma-cart-insurance.js
alma/views/js/alma-product-insurance.js

[Linear task](https://linear.app/almapay/issue/ECOM-1861/[🧩-ps]-fix-error-js-on-the-length-in-cart-if-product-is-not-eligible)
Check Eligibility Insurance before execute event of add to cart
Create a new product not eligible 
And add to cart this product, see if the product is right added in cart

fix: Issue insurance for product not eligible created after import

---

alma/views/js/alma-cart-insurance.js

[Linear task](https://linear.app/almapay/issue/ECOM-1866/[🧩-ps]-issue-if-we-change-the-quantity-in-the-cart-we-dont-update-it)
We moved the addEventListener in the root function and not in the prestashop event updatedCart
Chaneg the quantity in the cart item and add insurance.
See if we have the right quantity of insurance added

fix: Issue quantity insurance if we change quantity in cart

---

alma/controllers/hook/FrontHeaderHookController.php
alma/views/js/alma-insurance.js

[Linear task](https://linear.app/almapay/issue/ECOM-1880/[🧩-ps]-avoid-change-quantity-with-module-pscartdropdown-for-insurance)
The script for avoid change quantity on the mini cart wasn't returned.
We add a variable to increment scripts to add on the header
Install pscartdropdown module
Add insurance on your cart and try to change the quantity of the insurance

fix: Avoid change quantity with module pscartdropdown for insurance

---

.github/workflows/release-pull-request.yml

When release PRs are created by Github Action, the ci workflow is not triggered.
Until then it was triggered only because someone was adding a new commit to the Pull Request, but if no one commits to the release branch, CI is not triggered.
See the documentation explaining this here : https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#triggering-further-workflow-runs
I copied what we did in other repositories : We now use a Github App token 
Tested here: https://github.com/alma/alma-installments-prestashop/pull/524

[DEVX] Fix release PR not triggering workflows 

---

alma/alma.php
alma/controllers/hook/ActionAdminOrdersListingFieldsModifierHookController.php
alma/lib/Helpers/HookHelper.php

[Linear task](https://linear.app/almapay/issue/ECOM-1886/[🧩-ps]-add-column-in-orders-list-with-has-insurance)
We added a new hook to add insurance in the listing order for compatibility from PS 1.7
Make an order with insurance and see the listing orders of the backoffice and see the column has insurance with the value

[compatibility] feat: Add column in orders list with Has insurance

---

alma/alma.php

[Linear task](https://linear.app/almapay/issue/ECOM-1948/[-ps]-fix-install-alma-module-on-old-ps-version-if-symfony-isnt)
Add verification of Symfony ConfigCache for install module without Ps account
Identify from merchant

fix: install module without ConfigCache about PS Account

---

alma/views/templates/hook/notificationConfiguration.tpl

[Linear task](https://linear.app/almapay/issue/ECOM-1961/[-ps]-fix-display-multiple-notifications-dashboard-ps17)
We loop on all notification notification to hide is ps account isn't installed fir ps 1.7.0.6
Install our module on PS 1.7.0.6 and see there are no notification block duplicated

fix: display multiple notification dashboard on ps17

---

.github/workflows/ci.yaml
semgrep/rules/prestashop-compatibility-no-use-keyword.yaml

https://linear.app/almapay/issue/ALF-135/add-verification-during-release-prestashop-cms
* Add a semgrep rule
* There will only be an error if there is a `use something;` statement in file alma.php
*  No error is triggered if the use statement is commented, or if there is the string "use" somewhere in the file
* Other files than `alma.php` are not checked as this is the only one concerned by this constraint
* Run semgrep in CI (for people who did not set pre-commit)

[ALF-135] Add a semgrep rule to ensure compatibility with Prestashop v1.6

---

alma/lib/Helpers/FeePlanHelper.php
alma/tests/Unit/Helper/FeePlanHelperTest.php

[Linear task](https://linear.app/almapay/issue/ECOM-1743/absolution-minimum-payment)
The equal limit of feePlans are now eligible
Buy a product of equal limit of eligibility feePlan

fix: eligible limit of feePlans

---

alma/controllers/front/payment.php
alma/lib/Helpers/ProductHelper.php
alma/lib/Model/CartData.php
alma/tests/Unit/Helper/ProductHelperTest.php
alma/tests/Unit/Model/CartDataTest.php

[Linear task](https://linear.app/almapay/issue/ECOM-1882/hexamed-materiel-medical-error-when-making-a-payment)
We add helper to get category name of array or objet for create payment
Issue identify by a merchant, tested in the merchant store

fix: create payment with object category in product

---

alma/views/js/alma-product-insurance.js
alma/views/templates/hook/notificationConfiguration.tpl

[Linear task](https://linear.app/almapay/issue/ECOM-1974/fix-insurance-compatibility-170)
We change the event listener to identify the event when the modal add to cart is close for compatibility with PS 1.7
We add a loop to identify if there are a multiple notification block of first install and remove other in JS
In PS 1.7.0.6 :
- install our module and see after link with PS account if there are more that one notification block about first installation
- Add product with insurance and after add to cart close the modal about add to cart and see if the insurance widget is reset and there is no error in the console of the browser

fix: compatibility 1.7.0

---

.github/workflows/hotfix-pull-request.yml
.github/workflows/release-publish.yml
.github/workflows/release-pull-request.yml

ECOM integrations team is likely to update the release draft body before publishing it as it is targeted to a public audience.
When updating it, it is easy to click on the big flashy button "Publish release" instead of the grey button "Save draft"
This cannot be undone from the UI, and this shouldn't make the release-publish workflow fail
* Update release-publish workflow : If no release draft is found, fetch the latest release and go on with it if the version matches
* Update release/hotfix PR checklist: Add a warning to avoid misclick (even if handled, it is best not to publish the release before it is ready)

[DEVX] Check latest release if no release draft to be published

---

alma/views/js/alma-inpage.js

[Linear task](https://linear.app/almapay/issue/ECOM-2057/[-ps]-fix-inpage-on-prestashop-16-with-third-party-module-of-checkout)
We added a stopPropagation in event click payment button on Prestashop 1.6 for fix an parent event for some third party module of checkout
Need to test in the merchant env

fix: Inpage on prestashop 1.6 with third party module of checkout

---

alma/alma.php
alma/controllers/hook/FrontHeaderHookController.php
alma/exceptions/CompatibilityPsAccountException.php
alma/tests/Unit/Controllers/Front/index.php

[Linear task](https://linear.app/almapay/issue/ECOM-2056/[-ps]-fix-install-module-if-container-of-getservice-ps-account-is-null)
We refactored the checkout compatibility of Ps Account
Now we throw an exception if the shop isn't compatible to avoid any error into installation
Bug identify in the merchant

fix: install module if container of getService Ps_account is null

---

alma/composer.json
alma/controllers/front/ipn.php
alma/controllers/front/validation.php
alma/exceptions/PaymentValidationException.php
alma/lib/Builders/Validators/PaymentValidationBuilder.php
alma/lib/Helpers/ShareOfCheckoutHelper.php
alma/lib/Traits/BuilderTrait.php
alma/lib/Validators/PaymentValidation.php
alma/tests/Unit/Controllers/Front/IpnTest.php
alma/tests/Unit/Validators/PaymentValidationTest.php

[Linear task](https://linear.app/almapay/issue/ECOM-1818/[-ps]-add-hmac-verification-on-ipn)
We add the call function to `isHmacValidated` in php client to check is the IPN callback is signed by Alma before to validate the order by IPN
Make an order, close the page before the return validation payment
Call the ipn callback with some other browser or API Client to check if the IPN need the Alma signature

feat: HMAC verification on IPN callback for security

---

alma/lib/Helpers/PaymentOptionHelper.php
alma/lib/Helpers/PlanHelper.php
alma/lib/Services/PaymentService.php
alma/tests/Unit/Helper/PlanHelperTest.php

Rename variable to make code clearer

chore(naming): rename function to be clearer

---

alma/controllers/admin/AdminAlmaInsuranceConfiguration.php
alma/exceptions/CartException.php
alma/exceptions/InsuranceProductException.php
alma/exceptions/ProductException.php
alma/lib/Builders/Services/InsuranceProductServiceBuilder.php
alma/lib/Factories/CartFactory.php
alma/lib/Helpers/ProductHelper.php
alma/lib/Repositories/AlmaInsuranceProductRepository.php
alma/lib/Services/CartService.php
alma/lib/Services/InsuranceProductService.php
alma/lib/Traits/BuilderTrait.php
alma/tests/Unit/Factories/CartFactoryTest.php
alma/tests/Unit/Helper/AddressHelperTest.php
alma/tests/Unit/Helper/ProductHelperTest.php
alma/tests/Unit/Services/CartServiceTest.php
alma/tests/Unit/Services/InsuranceProductServiceTest.php

[Linear task](https://linear.app/almapay/issue/ECOM-2003/ps-remove-insurance-in-cart-when-deactivated)
Change state insurance product according insurance config state
Delete insurance product in cart if insurance is disable
Add insurance product in cart
Disable insurance in the configuration
See the insurance product is disable in the product list in back office
See the insurance product is deleted in the same cart

feat: Remove insurance in cart when deactivated

---

alma/controllers/front/payment.php
alma/controllers/hook/DisplayPaymentHookController.php
alma/lib/Helpers/ConfigurationHelper.php
alma/lib/Helpers/PaymentOptionHelper.php
alma/lib/Helpers/PaymentOptionTemplateHelper.php
alma/lib/Model/PaymentData.php
alma/lib/Services/PaymentService.php
alma/tests/Unit/Helper/ConfigurationHelperTest.php

[Linear task](https://linear.app/almapay/issue/ECOM-2070/[-ps]-integrate-credit-for-in-page)
I removed the condition to bloque inpage on credit.
Run unit tests locally.
Connect to the [QA env](https://credit-inpage-qa-prestashop-1-7-8-7.integrations.getalma.eu/), check if inpage is activated, add a product to the cart, go to the checkout and try to pay with the p10x.

Integrate credit for in page

---

alma/alma.php

[Linear task](https://linear.app/almapay/issue/ECOM-2112/[-ps]-fix-setcontainer-ps-account-install-module)
We set the container also in the install fonction
Install the module in CI without debug mode

fix: setContainer Ps Account install module

---

alma/lib/Helpers/HookHelper.php
alma/views/css/alma-insurance.css
alma/views/js/alma-product-insurance.js
alma/views/templates/hook/displayProductActions.tpl

[Linear task](https://linear.app/almapay/issue/ECOM-2095/[-ps]-fix-handle-height-insurance-widget)
By default we define the height of widget at 100%
And we remove the hack about the height data send in postMessage if lower that 45px
Display the widget in the product page
Change the product reference
Change the quantity
See if the widget is updated with the height and data
Remove the product in the cart to see if the product and insurance are removed
[Link to the infra for QA](https://qa-fix-widget-insurance-prestashop-1-7-8-7.integrations.getalma.eu)

fix: automatic height insurance widget

---

alma/controllers/hook/DisplayProductActionsHookController.php
alma/views/js/alma-product-insurance.js

In some versions of PrestaShop (here, 1.7.2.4), the insurance widget is reloaded in an infinite loop:
https://github.com/user-attachments/assets/b9b2d58d-13bf-4440-b7d2-fd87d125d753
In some other versions (e.g. 1.7.0.6) the reloading only inexplicably happens once instead of infinitely, i.e. 2 consecutive loading of the widget, so 1 extra load.
The root cause for both seems to be the use of PrestaShop events paired with messaging management from the widget iframe.
As a side effect, the whole product details & add to cart section of the product page is reloaded unnecessarily, including our BNPL widget, which makes the sidebar's height jump up & down.
Fixes [ECOM-2184](https://linear.app/almapay/issue/ECOM-2184)
- Started by documenting existing code to better grasp its inner workings
- …

Improve insurance integration stability & prevent unnecessary reloading of widget

---

alma/alma.php
alma/controllers/hook/GetContentHookController.php
alma/exceptions/CompatibilityPsAccountsException.php
alma/translations/de.php
alma/translations/en.php
alma/translations/es.php
alma/translations/fr.php
alma/translations/it.php
alma/translations/nl.php
alma/translations/pt.php
alma/views/templates/hook/getContent.tpl
alma/views/templates/hook/notificationConfiguration.tpl

[Linear task](https://linear.app/almapay/issue/ECOM-2162/zepelucheclubcom-500-internal-sever-error)
We added a verification version of PS Account. If PS Account was lower that 5.0 PS Account Service returned an error that we didn't handle.
Now if the version is lower 5.0 we suggest to install the PS Account module (default message)
Install Ps Account lower that 5.0.
Install our module.
Try to configure it

fix: Impossible configure Alma if PS Account version is lower  5.0

---

alma/lib/Helpers/PaymentOptionTemplateHelper.php
alma/lib/Helpers/PlanHelper.php
alma/lib/Helpers/TranslationHelper.php
alma/tests/Unit/Helper/PaymentOptionTemplateHelperTest.php
alma/tests/Unit/Helper/TranslationHelperTest.php
alma/translations/en.php
alma/translations/fr.php

[Linear task](https://linear.app/almapay/issue/ECOM-2147/eurl-mecatera-word-in-english-in-the-checkout-module)
We created an helper to test some function with translations. But Prestashop doesn't handle the translation is the function doesn't named `->l()` I renamed our function with `->l()` to handle all our translation
Install the FR language un the store `Translation > Add / Update a language > Add French`
Install our module and enable de Pay later (+15/+30)
Go to the front, change the langue in FR
Go to the checkout, select a pay later and see if the payment button pay later is well translated.

fix: issue with some translation in payment buttons

---

alma/views/js/alma-product-insurance.js

Some e-commerce merchants remove the quantity input from the product page because it does not make sense to purchase their products multiple times (e.g. bikes, sofas)
Our current insurance code crashes when this is the case.
Fixes [ECOM-2200](https://linear.app/almapay/issue/ECOM-2200)
- Simply check whether we find an actual input before trying to read its value
- Open a product page
- Remove the quantity input from the DOM using the developer tools
- Use the insurance widget & add a product to the cart : it should work

Prevent crash when there is not quantity input on product page

---

alma/controllers/front/cmsdataexport.php
alma/lib/Helpers/CmsDataHelper.php
alma/tests/Unit/Helper/CmsDataHelperTest.php
alma/upgrade/upgrade-4.6.0.php

[Linear task](https://linear.app/almapay/issue/ECOM-2240/[-ps]-send-the-endpoint-url-during-the-upgrade-of-the-module)
- We send the endpoint url during the update of the module 4.6.0
- We normalized the payload returned for the gather CMS data
- We return null in the used_fee_plans key if the array is empty
- Update the module in version 4.6.0 and see if the endpoint url is sent to Alma
- Check the data returned for Gather CMS Data without the `success` key
- Check the unit test about the data returned if used_fee_plans is an array empty

feat: Send the endpoint_url during the upgrade

---

alma/controllers/hook/DisplayRefundsHookController.php
alma/controllers/hook/StateHookController.php
alma/lib/Helpers/OrderHelper.php
alma/lib/Helpers/ShareOfCheckoutHelper.php

[Linear task](https://linear.app/almapay/issue/ECOM-2266/groupe-h4-error-when-consulting-payments)
Inject Module Class in OrderHelper to use the l() function for the translation
Make an order with valid order value at false and change the status of this order

fix: inject Module in OrderHelper to use translation function

---

alma/lib/Helpers/ContextHelper.php
alma/tests/Unit/Helper/ContextHelperTest.php

Fix our unit test because an update of the module ps_checkout break our test who wasn't really unit

fix: unit test for context link issue from ps_checkout module

---

alma/lib/Helpers/CmsDataHelper.php
alma/lib/Model/AlmaModuleModel.php
alma/tests/Unit/Helper/CmsDataHelperTest.php
alma/tests/Unit/Model/AlmaModuleModelTest.php

[Linear task](https://linear.app/almapay/issue/ECOM-2373/via-prestashop-get-alma-payment-positionranking-at-checkout)
We added function to getPosition of alma in hook paymentOptions for PS 1.7 and displayPayment for PS 16
BackOffice :
Install the module
Go to Design->position
Search the hook paymentOptions for PS1.7 or displayPayment for PS 1.6
Change the position of alma in the hook
Front:
Make Get of Gather CMS Data (with postman) and check the value of `payment_method_position`
Change the position and check again the return (in postman)

feat: Add position at checkout for GatherCMSData

---

alma/lib/Model/AlmaBusinessDataModel.php
alma/lib/Model/AlmaObjectModel.php
alma/lib/Model/InsuranceProduct.php
alma/lib/Repositories/AlmaBusinessDataRepository.php
alma/tests/Unit/Services/AlmaBusinessDataServiceTest.php

[Linear task](https://linear.app/almapay/issue/ECOM-2414/[-ps]-fix-merchant-business-event-for-ps-16)
In old PS version the ObjectModel wasn't compatible 
Add AlmaObjectModel to fix the issue
Set alma_payment_id at null for the creation
Up an infra with PS 1.6
Add product in cart
Check in db if the insert is right

fix: create AlmaObjectModel for compatibility with PS1.6 + remove unique key alma_payment_id

---

alma/alma.php
alma/controllers/hook/ActionCartSaveHookController.php
alma/controllers/hook/ActionValidateOrderHookController.php
alma/lib/Repositories/AlmaBusinessDataRepository.php
alma/lib/Services/AlmaBusinessDataService.php
alma/tests/Unit/Services/AlmaBusinessDataServiceTest.php
alma/upgrade/upgrade-4.7.1.php

[Linear task](https://linear.app/almapay/issue/ECOM-2416/[prestashop]-deduplicate-business-event-calls)
We check before business event if table exist
If table doesn't exist we create it
If we can't create it we don't send the business event call
Try to remove the table before to add product in cart and check if the table is created

fix: Deduplicate business event calls

---

alma/lib/Helpers/ThemeHelper.php

[Linear task](feature/ecom-2490-ps-fix-force-type-to-string-for-cms_datatheme_version)
Add string type to getThemeVersion return.
Add isset to avoid fatal errors on non-existing index

Fix force type to string for cms datatheme version

---

alma/controllers/hook/StateHookController.php
alma/exceptions/OrderServiceException.php
alma/lib/Helpers/ClientHelper.php
alma/lib/Services/OrderService.php
alma/lib/Validators/PaymentValidation.php
alma/tests/Unit/Helper/ClientHelperTest.php
alma/tests/Unit/Services/OrderServiceTest.php

[Linear task](https://linear.app/almapay/issue/ECOM-2385/[ps]-use-the-new-endpoint-for-order-status)
Remove get payment
Replace v2/orders/... enpoint by v1/payment/.../orders/.../status endpoint.

Use new payment endpoint for order status

---

alma/views/js/alma-inpage.js

[Linear task](https://linear.app/almapay/issue/ECOM-2508/prestashop-integration-the-basket-does-not-load)
We execute in-page when in payment option is checked even after load page instead of only when the page in loaded
Test in the merchant store

fix: handle In-page if payment option is checked before page loaded

---

alma/controllers/hook/ActionCartSaveHookController.php

[Linear task](https://linear.app/almapay/issue/ECOM-2626/merchant-has-an-issue-with-the-module)
Inject Validate without `use`  but add \ for validate with old Prestashop version
Add to cart in old prestashop version < 1.7

fix: Validate injection for old Prestashop version

---

alma/lib/Services/OrderService.php
alma/tests/Unit/Services/OrderServiceTest.php

[Linear task](https://linear.app/almapay/issue/ECOM-2737/investigate-drop-in-order-status-data-coverage-on-prestashop)
Our data about is_shipped return by Prestashop was O or 1, but our request needed bool, we added type force in bool and update test
Make an order, change the status and check the data send

fix: Shipment data type error

---

alma/alma.php
alma/lib/Helpers/HookHelper.php

[Linear task](https://linear.app/almapay/issue/ECOM-2746/prestashop-174-displayproductactionshookcontrollerphp)
We removed the call to the hook DisplayProductActions because it removed from Insurance removed
Install Prestashop before 1.7.6 from an old version of our module (2.12.0) and update it to the last version

fix: Unregister hook DisplayProductActions
