- alma/controllers/hook/DisplayShoppingCartFooterHookController.php
- alma/lib/Utils/Settings.php
- alma/translations/fr.php
fixing wrong translations (minium/maximum amount)
> fix bad translations

- alma/lib/Model/PaymentData.php
- alma/lib/Model/ShippingData.php
shipping info now is a mutli array. Need change in Alma API
> FIX : allow mulit carrier in  shipping info dat

- alma/alma.php
- alma/controllers/front/ipn.php
- alma/controllers/hook/FrontHeaderHookController.php
- alma/lib/Model/PaymentData.php
version 1.5.3.1 : payment works but no widget on product page
version > 1.5.3.1 : all good :)
> alma works with version 1.5.3.1+ now

- alma/lib/Hooks/HookController.php
fix bug : order's status was missing
> fix: missing order status after payment

- alma/alma.php
- alma/controllers/admin/AdminAlmaRefunds.php
* refactor: reduce alma::install < 3 returns [sonar issue](https://sonarcloud.io/project/issues?issues=AX2UDHEZmr1hAwh33909&open=AX2UDHEZmr1hAwh33909&id=alma_alma-installments-prestashop)
> 2022 02 25 tech debt fight session

- .github/workflows/e2e-test.yaml
> Add trigger on e2e tests

- alma/controllers/hook/GetContentHookController.php
- alma/lib/Forms/AbstractAdminFormBuilder.php
- alma/lib/Forms/PaymentOnTriggeringAdminFormBuilder.php
- alma/views/css/admin/almaPage.css
- alma/views/templates/admin/_configure/helpers/form/15/form.tpl
- alma/views/templates/admin/_configure/helpers/form/form.tpl
Hide Payment upon trigger if is disabled
> hide payment upon trigger

- alma/lib/Utils/CustomFieldsHelper.php
- alma/translations/de.php
- alma/translations/en.php
- alma/translations/es.php
- alma/translations/fr.php
- alma/translations/it.php
- alma/translations/nl.php
- alma/translations/pt.php
[ClickUp task](https://app.clickup.com/20427503/v/b/4-32476982-2/CLICKUP_ISSUE_ID)
> wording pay now

- .github/workflows/e2e-test.yaml
[ClickUp task](https://app.clickup.com/20427503/v/b/4-32476982-2/CLICKUP_ISSUE_ID)
> fix : e2e tests not on draft

- .github/workflows/e2e-test.yaml
[ClickUp task](https://app.clickup.com/20427503/v/b/4-32476982-2/CLICKUP_ISSUE_ID)
> master to main

- alma/views/js/alma-inpage.js
[fix jQuery for GPMA](https://linear.app/almapay/issue/MPP-529/fix-jquery-for-gpma)
remove true in noConflict
Tested in environnement GPMA
> Fix/mpp 529/fix jquery for gpma

- alma/views/js/alma-inpage.js
[Fix issue In-Page GPMA](https://linear.app/almapay/issue/MPP-658/fix-issue-in-page-gpma)
fix error message dom for inpage without eligibility
Go Checkout page with inpage with no eligibility
> fix error massage inpage gpma

- CHANGELOG.md
- alma/views/js/alma-inpage.js
[fix inpage KService](https://linear.app/almapay/issue/MPP-657/fix-in-page-k-service)
In-Page in KService website
Test in environment of the merchant
> fix inpage kservice

- alma/views/js/alma-inpage.js
[Linear task](https://linear.app/almapay/issue/MPP-743/maison-aubertin-issue-with-in-page)
change window load for fix inpage some merchant
Need the merchant env to test
> Maison Aubertin - Issue with In page

- CHANGELOG.md
- alma/CHANGELOG.md
- alma/views/js/alma-inpage.js
- alma/views/templates/front/index.php
> Release 3.1.0

- alma/.htaccess
[Linear task](https://linear.app/almapay/issue/MPP-841/add-htaccess-in-root-module)
To prevent someone from listing the module files, an .htaccess file must be present in the root folder. See the documentation
We can test, it's recommendation of Prestashop
> Add htaccess in root module

- alma/alma.php
- alma/controllers/hook/ActionCartSaveHookController.php
- alma/controllers/hook/ActionValidateOrderHookController.php
- alma/exceptions/InsuranceNotFoundException.php
- alma/lib/Helpers/ConstantsHelper.php
- alma/lib/Helpers/HookHelper.php
- alma/lib/Repositories/AlmaInsuranceProductRepository.php
- alma/lib/Repositories/AttributeGroupRepository.php
- alma/lib/Repositories/AttributeRepository.php
- alma/lib/Repositories/ProductRepository.php
- alma/views/templates/hook/displayProductActions.tpl
[Linear task](https://linear.app/almapay/issue/MPP-760/investigate-feasibilityhow-to-add-an-insurance-product-into-customers)
Add insurance product to cart
> Feature/mpp 760/investigate feasibilityhow to add an insurance product into customers

- alma/controllers/admin/AdminAlmaInsuranceOrders.php
[Linear task](https://linear.app/almapay/issue/MPP-857/list-the-orders-with-insurance-without-link)
Create a paginated, sortable list with the following columns:
- id_order
- id_product
- id_shop
- id_product_attribute
- id_customization
- id_product_insurance
- id_product_attribute_insurance
- price
- date_add
Display the Order Insurance Page to see the table
> List the orders with Insurance without link

- alma/views/css/alma-insurance.css
- alma/views/templates/hook/displayProductActions.tpl
[Linear task](https://linear.app/almapay/issue/MPP-936/improve-widget-integration-design)
Add CSS to display the widget insurance under the payment button and in full width and height.
Display the widget insurance in product page
> Improve Widget intégration design

- alma/views/css/admin/almaPage.css
- alma/views/templates/admin/insurance.tpl
[Linear task](https://linear.app/almapay/issue/MPP-959/update-iframe-back-office)
Fix Height Iframe BO config insurance
Display the BO config insurance
> Fix height iframe BO

- alma/alma.php
- alma/controllers/hook/ActionCartSaveHookController.php
- alma/controllers/hook/DisplayCartExtraProductActionsHookController.php
- alma/lib/Helpers/HookHelper.php
- alma/lib/Repositories/AlmaInsuranceProductRepository.php
- alma/views/css/alma-insurance.css
- alma/views/js/alma-cart.js
- alma/views/js/alma-product.js
- alma/views/templates/hook/displayCartExtraProductActions.tpl
[Linear task](https://linear.app/almapay/issue/MPP-1001/add-display-in-cart-for-insurance-management)
Add template handle insurance under product item cart
Add Insurance in cart and display the cart.
Try to handle insurance with the product
> Add display in cart for insurance management

- alma/views/css/alma-insurance.css
- alma/views/js/alma-product.js
[Linear task](https://linear.app/almapay/issue/MPP-1024/update-insurance-product-page-after-buying)
Handle input insurance on the product page
Buy a product with the insurance and don't redirect you to the cart page and see if the input are removed after the product added in cart
> Update insurance product page after buying

- alma/controllers/hook/ActionCartSaveHookController.php
- alma/controllers/hook/DisplayCartExtraProductActionsHookController.php
- alma/lib/Repositories/ProductRepository.php
- alma/lib/Services/CombinationProductAttributeService.php
- alma/lib/Services/InsuranceProductService.php
- alma/lib/Services/InsuranceService.php
Manage Insurance Stock
[Linear task](https://linear.app/almapay/issue/MPP-984/manage-insurance-product-stock)
> Manage Stock

- alma/lib/Services/AttributeProductService.php
Attribute Model has change name
[Linear task](https://linear.app/almapay/issue/MPP-1053/fix-insurance-on-prestashop-8)
Add product with insurance to cart
> Feature/mpp 1053/fix insurance on prestashop 8

- alma/views/js/alma-product-insurance.js
[Linear task](https://linear.app/almapay/issue/ECOM-1154/good-amount-in-the-modal-if-we-change-the-quantity-before-add-to-cart)
Add quantity on function to open the modal insurance
Change the quantity before to click to add to cart and see the price of the insurance
> [insurance] Good amount in the modal if we change the quantity before add to cart

- CHANGELOG.md
- alma/alma.php
- alma/lib/Validators/PaymentValidation.php
Hotfix order validated with payment refunded
warroom : war-room_inc-434_2024-01-23_prestashop-orders-with-mismatch-are-full-refund
[Linear task](https://linear.app/almapay/issue/ECOM-1246/🏃-mon-lit-cabane-mismatch)
> hotfix : fix order validated with payment refunded

- .github/workflows/e2e-test.yaml
- CHANGELOG.md
- alma/alma.php
- alma/composer.json
- alma/controllers/admin/AdminAlmaRefunds.php
- alma/views/templates/hook/order_refund_bs3.tpl
- alma/views/templates/hook/order_refund_bs4.tpl
- alma/views/templates/hook/order_refund_ps15.tpl
[Add verification type number on field amount](https://github.com/alma/alma-installments-prestashop/pull/295)
> Release 3.1.5

- alma/composer.json
[Linear task](https://linear.app/almapay/issue/ECOM-1297/[issue-github]-compatibility-with-composer)
We updated composer.json.
We compare with the [Prestashop documentation](https://devdocs.prestashop-project.org/8/modules/concepts/composer/)
> [develop] Compatibility with composer

- alma/views/js/alma-order-insurance.js
[Linear task](https://linear.app/almapay/issue/ECOM-1376/[🧩-ps]-issue-opt-in-first-load-page)
Rebuild code term and condition opt in in jquery
Add to cart an insurance and click to the opt in term to open de docs
> [insurance] Issue opt in first load page

- alma/controllers/front/subscription.php
- alma/exceptions/MessageOrderException.php
- alma/lib/Helpers/MessageOrderHelper.php
- alma/lib/Helpers/SubscriptionHelper.php
- alma/lib/Repositories/AlmaInsuranceProductRepository.php
- alma/lib/Repositories/CustomerThreadRepository.php
- alma/lib/Services/MessageOrderService.php
- alma/tests/Unit/Helper/MessageOrderHelperTest.php
- alma/tests/Unit/Services/MessageOrderServiceTest.php
[Linear task](https://linear.app/almapay/issue/ECOM-1234/[🧩-ps]-display-notification-when-a-subscription-has-been-canceled)
> [insurance_refund] Display notification when a subscription has been canceled

- alma/controllers/admin/AdminAlmaInsuranceOrders.php
- alma/controllers/admin/AdminAlmaInsuranceOrdersDetails.php
- alma/views/css/admin/almaPage.css
Retours sur les debugs https://www.notion.so/almapay/Manual-QA-Insurance-MVP-Refunds-a29d24cf92b04a4da3541179db5c36dd
> Display warning on order + fixes

- alma/alma.php
- alma/composer.json
- alma/controllers/admin/AdminAlmaInsuranceOrders.php
- alma/controllers/front/subscription.php
- alma/controllers/hook/ActionOrderGridDefinitionModifierHookController.php
- alma/controllers/hook/ActionOrderGridQueryBuilderModifierHookController.php
- alma/controllers/hook/DisplayAdminOrderTopHookController.php
- alma/lib/Helpers/InsuranceHelper.php
- alma/lib/Repositories/AlmaInsuranceProductRepository.php
- alma/lib/Services/InsuranceService.php
- alma/views/js/admin/alma-insurance-subscriptions.js
[Linear task](https://linear.app/almapay/issue/ECOM-1453/fix-create-subscription-url-for-webhook)
> [insurance_refund] Fix create subscription url for webhook

- docker-compose.yml
[Linear task](https://linear.app/almapay/issue/ECOM-1503/[🧩-ps]-fix-sonarcloud-issues)
change language install docker prestashop
launch Make  test
> Fix SonarCloud issues

- CHANGELOG.md
- alma/controllers/hook/DisplayPaymentHookController.php
- alma/controllers/hook/PaymentOptionsHookController.php
- alma/lib/Helpers/ApiHelper.php
- alma/lib/Model/PaymentData.php
- alma/lib/Validators/PaymentValidation.php
- alma/views/js/alma-inpage.js
- alma/views/templates/front/payment_form_inpage.tpl
- alma/views/templates/hook/_partials/displayPayment_deferred.tpl
- alma/views/templates/hook/_partials/displayPayment_pnx.tpl
- alma/views/templates/hook/payment_button_deferred.tpl
- alma/views/templates/hook/payment_button_pnx.tpl
[Linear task](https://linear.app/almapay/issue/ECOM-1458/[%F0%9F%A7%A9-ps]-remove-restriction-to-filter-out-deferred-payments-from-in)
Activate deferred payment and In page checkout for Presta 1.6 and 1.7, check if it works
> Remove restriction to filter out deferred payments 

- alma/controllers/hook/DisplayPaymentHookController.php
- alma/controllers/hook/GetContentHookController.php
- alma/controllers/hook/PaymentOptionsHookController.php
- alma/lib/Forms/PnxAdminFormBuilder.php
- alma/lib/Helpers/SettingsHelper.php
- alma/lib/Validators/PaymentValidation.php
- alma/phpunit.ci.xml
- alma/phpunit.dist.xml
- alma/tests/Unit/Helper/SettingsHelperTest.php
[Linear task](https://linear.app/almapay/issue/ECOM-1518/[%F0%9F%A7%A9-ps]-test-functions-settingshelper-getduration)
> Add test functions settingshelper getduration

- alma/controllers/hook/DisplayPaymentHookController.php
- alma/controllers/hook/DisplayProductPriceBlockHookController.php
- alma/controllers/hook/DisplayShoppingCartFooterHookController.php
- alma/controllers/hook/PaymentOptionsHookController.php
- alma/lib/Helpers/LanguageHelper.php
- alma/lib/Helpers/LocaleHelper.php
- alma/tests/Unit/Helper/LocaleHelperTest.php
- docker-compose.yml
[Linear task](https://linear.app/almapay/issue/ECOM-1512/[%F0%9F%A7%A9-ps]-test-functions-localhelper)
> add tests for LocaleHelper->getLocaleByIdLangForWidget

- alma/controllers/hook/DisplayPaymentHookController.php
- alma/controllers/hook/GetContentHookController.php
- alma/controllers/hook/PaymentOptionsHookController.php
- alma/controllers/hook/StateHookController.php
- alma/lib/Forms/PnxAdminFormBuilder.php
- alma/lib/Helpers/ConfigurationHelper.php
- alma/lib/Helpers/SettingsHelper.php
- alma/lib/Helpers/ShopHelper.php
- alma/lib/Validators/PaymentValidation.php
- alma/tests/Unit/Helper/SettingsHelperTest.php
[Linear task](https://linear.app/almapay/issue/ECOM-1520/[%F0%9F%A7%A9-ps]-test-functions-settingshelper-isdeferredtriggerlimitdays)
> Test functions settingshelper isdeferredtriggerlimitdays

- alma/controllers/hook/DisplayPaymentHookController.php
- alma/controllers/hook/GetContentHookController.php
- alma/controllers/hook/PaymentOptionsHookController.php
- alma/lib/Helpers/SettingsHelper.php
- alma/tests/Unit/Helper/SettingsHelperTest.php
[Linear task](https://linear.app/almapay/issue/ECOM-1515/[%F0%9F%A7%A9-ps]-test-functions-settingshelper-keyforinstallmentplan)
> Test functions settingshelper keyforinstallmentplan

- alma/controllers/admin/AdminAlmaCategories.php
- alma/controllers/hook/DisplayPaymentHookController.php
- alma/controllers/hook/DisplayProductPriceBlockHookController.php
- alma/controllers/hook/DisplayShoppingCartFooterHookController.php
- alma/controllers/hook/GetContentHookController.php
- alma/controllers/hook/PaymentOptionsHookController.php
- alma/lib/Forms/ExcludedCategoryAdminFormBuilder.php
- alma/lib/Forms/PnxAdminFormBuilder.php
- alma/lib/Helpers/SettingsHelper.php
- alma/lib/Model/CartData.php
- alma/lib/Validators/PaymentValidation.php
- alma/tests/Unit/Helper/SettingsHelperTest.php
[Linear task](https://linear.app/almapay/issue/ECOM-1532/[%F0%9F%A7%A9-ps]-test-functions-settingshelper-getexcludedcategories)
> add tests SettingsHelper getExcludedCategories

- alma/tests/Unit/Helper/DateHelperTest.php
[Linear task](https://linear.app/almapay/issue/ECOM-1516/%5B%F0%9F%A7%A9-ps%5D-test-functions-datehelper-getdateformat)
> [develop] add tests getDateFormat

- alma/lib/Repositories/AlmaInsuranceProductRepository.php
- alma/views/js/alma-cart-insurance.js
[Linear task](https://linear.app/almapay/issue/ECOM-1604/[🧩-ps]-fix-insurance-for-odp)
Disable item insurance product in cart
Issue with same insurance ordered in the same time
Hide button +/- on the field quantity of the product if there is a insurance in the cart page
> Fix insurance for ODP

- alma/controllers/admin/AdminAlmaInsuranceOrdersDetails.php
- alma/views/js/admin/alma-insurance-subscriptions.js
[Linear task](https://linear.app/almapay/issue/ECOM-1608/[🧩-ps]-fix-isrefunded-param-sent-to-ifram)
Change isRefund value from string to bool
Make a insurance avoid and see the wording about the refund
> [insurance] Fix isrefunded param sent to ifram

- alma/tests/Unit/Helper/ConfigurationHelperTest.php
[Linear task](https://linear.app/almapay/issue/ECOM-1574/[%F0%9F%A7%A9-ps]-unit-configurationhelpertest)
> Configurationhelpertest

- alma/lib/Helpers/PlanHelper.php
- alma/tests/Unit/Helper/PlanHelperTest.php
[Linear task](https://linear.app/almapay/issue/ECOM-1584/[%F0%9F%A7%A9-ps]-unit-planhelpertest)
> unit planhelpertest

- alma/tests/Unit/Helper/ConfigurationHelperTest.php
- alma/tests/Unit/Helper/PlanHelperTest.php
- alma/tests/Unit/Helper/ToolsHelperTest.php
- alma/views/js/alma-product-insurance.js
[Linear task](https://linear.app/almapay/issue/ECOM-1651/[🧩-ps]-fix-display-insurance-widget-if-id-product-attribute-equal)
We create the cms_reference in js file with the same restriction of code back. If id_product_attribute eqal zero we don't send the id_product_attribute
Identify in the merchant ODP, Need to test on their website
> Fix display insurance widget if id product attribute

- alma/lib/Helpers/ProductHelper.php
- alma/tests/Unit/Helper/ConfigurationHelperTest.php
- alma/tests/Unit/Helper/PlanHelperTest.php
- alma/tests/Unit/Helper/ToolsHelperTest.php
[Linear task](https://linear.app/almapay/issue/ECOM-1652/[🧩-ps]-send-ttc-price-for-insurance-amount)
We use the native getPriceStatic function of Prestashop to have the price without reduction and with taxe
Go to a product page with taxe and reduction and see if the price send to the insurance widget is the price without reduction and with the taxe
> Send ttc price for insurance amount

- alma/views/templates/admin/insurance.tpl
- alma/views/templates/admin/insurance_order_details.tpl
- alma/views/templates/hook/displayProductActions.tpl
[Linear task](https://linear.app/almapay/issue/ECOM-1669/[🧩-ps]-fix-remove-id-in-type-of-script-of-insurance)
CloudFlare add an id in the type of script and we can't have an other type that "module" to make that the modal work fine.
We need to add data-cfasync="false" to avoid cloudflare to update the type
Fix for ODP, need to test in their Prod
> [ODP] Fix remove id in type of script of insurance

- alma/views/js/alma-product-insurance.js
[Linear task](https://linear.app/almapay/issue/ECOM-1671/[💅-ps]-fix-widget-insurance-force-quantity-1-if-=-0)
Fix quantity if quantity equal zero
Bug identify in the merchant ODP
> fix quantity if quantity equal zero

- alma/controllers/hook/FrontHeaderHookController.php
- alma/lib/Helpers/ConstantsHelper.php
- alma/views/js/alma-insurance.js
- alma/views/js/alma-product-insurance.js
[Linear task](https://linear.app/almapay/issue/ECOM-1663/[🧩-ps]-fix-handle-insurance-mini-cart-module-pscartdropdown)
We need to remove the handle quantity and link to the product in the mini cart for insurance product
We will handle it with a JS script helped by the id product of insurance.
We loop the item of mini cart and identify the item with the id product
Installe the module pscartdropdown and check the insurance product
> [IPLN] Fix handle insurance mini cart module pscartdropdown

- alma/phpunit-threshold.php
- alma/tests/Unit/Helper/TranslationHelperTest.php
[Linear task](https://linear.app/almapay/issue/ECOM-1587/[%F0%9F%A7%A9-ps]-unit-translationhelpertest)
make test
> REVIEW 3 :ps unit translationhelpertest

- .pre-commit-config.yaml
- Taskfile.yml
- alma/lib/API/index.php
- alma/lib/Helpers/ClientHelper.php
- alma/lib/Helpers/index.php
- alma/lib/Traits/index.php
- scripts/coding-standard-fixer.sh
- scripts/coding-standard.sh
- scripts/php-compatibility.sh
[DEX-807/prestashop-set-pre-commit](https://linear.app/almapay/issue/DEX-807/prestashop-set-pre-commit)
* Use tasks in pre-commit file
* Add checks : 
- lint checks for smarty templates variables non html escaped
- lint:fix run autoindex and ./scripts/remove-blank-line-index.sh
> [DEX-807]  Update pre commit file

- alma/lib/Builders/CustomFieldHelperBuilder.php
- alma/lib/Factories/ModuleFactory.php
- alma/lib/Helpers/CustomFieldsHelper.php
- alma/lib/Traits/BuilderTrait.php
- alma/tests/Unit/Builders/PaymentServiceBuilderTest.php
- alma/tests/Unit/Factories/ModuleFactoryTest.php
- alma/tests/Unit/Helper/CustomFieldHelperTest.php
[Linear task](https://linear.app/almapay/issue/ECOM-1578/[%F0%9F%A7%A9-ps]-unit-customfieldhelpertest)
make coverage
> REVIEW 9 : add customer fields helper tests

- alma/alma.php
- alma/controllers/admin/AdminAlmaInsuranceConfiguration.php
- alma/controllers/admin/AdminAlmaInsuranceOrdersDetails.php
- alma/controllers/hook/DisplayProductActionsHookController.php
- alma/controllers/hook/GetContentHookController.php
- alma/exceptions/WrongCredentialsException.php
- alma/exceptions/WrongParamsException.php
- alma/lib/Builders/Admin/InsuranceHelperBuilder.php
- alma/lib/Builders/ApiHelperBuilder.php
- alma/lib/Helpers/Admin/InsuranceHelper.php
- alma/lib/Helpers/ApiHelper.php
- alma/lib/Helpers/ClientHelper.php
- alma/lib/Traits/BuilderTrait.php
- alma/lib/smarty.php
- alma/tests/Unit/Builders/Admin/InsuranceHelperBuilderTest.php
- alma/tests/Unit/Builders/ApiHelperBuilderTest.php
- alma/tests/Unit/Helper/Admin/InsuranceHelperTest.php
- alma/tests/Unit/Helper/ApiHelperTest.php
[Linear task](https://linear.app/almapay/issue/ECOM-1571/[%F0%9F%A7%A9-ps]-unit-apihelpertest
make test
> REVIEW 11 :  ps unit apihelpertest

- .github/dependabot.yml
- .github/renovate.json
This PR targets the `main` branch for it to be readable for Renovate, but will push updates to the `develop` branch.
> [devx] Automatic updates using Renovate/Dependabot

- alma/controllers/hook/DisplayProductActionsHookController.php
- alma/lib/Helpers/ProductHelper.php
- alma/lib/Services/InsuranceProductService.php
- alma/views/js/alma-product-insurance.js
[Linear task](https://linear.app/almapay/issue/ECOM-1714/[🧩-ps]-fix-send-price-to-neat)
> Fix Send price to Neat

- alma/controllers/hook/DisplayProductActionsHookController.php
[Linear task](https://linear.app/almapay/issue/ECOM-1728/[🧩-ps]-fix-card-id-send-to-iframe-widget-insurance-url)
> Fix card_id send to iframe widget insurance url

- alma/lib/Services/InsuranceSubscriptionService.php
[Linear task](https://linear.app/almapay/issue/ECOM-1729/[🧩-ps]-fix-attach-rate-send-eligible-cart-from-insurance)
> Fix attach rate send eligible cart from insurance

- alma/lib/Services/InsuranceApiService.php
- alma/lib/Services/InsuranceSubscriptionService.php
[Linear task](https://linear.app/almapay/issue/ECOM-1731/[🧩-ps]-fix-for-send-payment-id-only-for-alma-payment)
> Fix for send payment_id only for Alma payment

- alma/controllers/hook/StateHookController.php
[Linear task](https://linear.app/almapay/issue/ECOM-1727/[🧩-ps]-explo-if-the-status-is-changed-quickly-after-the-payment-has)
> add log on trigger payment

- alma/controllers/hook/StateHookController.php
[Linear task](https://linear.app/almapay/issue/ECOM-1736/[🧩-ps]-fix-handle-execute-trigger-insurance-from-frontoffice)
Edit CanRun for employeeLogged for change states order
Buy insurance in prod with an user not logged on the dashboard
> fix trigger insurance

- alma/alma.php
- alma/views/templates/hook/getContent.tpl
[Linear task](https://linear.app/almapay/issue/ECOM-1710/%5B%F0%9F%A7%A9-ps%5D-ps-account-fix-16)
[Hide form](https://linear.app/almapay/issue/ECOM-1708/[%F0%9F%A7%A9-ps]-hide-config-when-merchant-is-no-connected)
> fix PS account

- alma/lib/Helpers/EligibilityHelper.php
[Linear task](https://linear.app/almapay/issue/ECOM-1743/%F0%9F%8F%83-absolution-minimum-payment)
Configure your min amount to 100, add 100euros to your cart, alma must appeat in checkout page
> [HOTFIX] fix wrong minimum fee plan condition

- alma/controllers/hook/ActionCartSaveHookController.php
- alma/lib/Helpers/InsuranceHelper.php
- alma/lib/Repositories/AlmaInsuranceProductRepository.php
- alma/lib/Repositories/CartSaveRepository.php
- alma/lib/Services/CartSaveService.php
- alma/lib/Services/InsuranceProductService.php
- alma/tests/Unit/Helper/InsuranceHelperTest.php
- alma/tests/Unit/Services/CartSaveServiceTest.php
- alma/tests/Unit/Services/InsuranceProductServiceTest.php
[Linear task](https://linear.app/almapay/issue/ECOM-1691/[🧩-ps]-fix-compatibility-with-a-savecart-module)
Add specific code for compatibility with the module opartSaveCart and Insurance
Installe the module OpartSaveCart
Save the cart
Get the cart saved
Change your current cart
And re-get your cart saved
> [insurance-beta] savecart module with insurance before release

- alma/controllers/hook/GetContentHookController.php
[Linear task](https://linear.app/almapay/issue/ECOM-1752/[ps]-bug-on-configuration-page)
Run e2e tests
> fix rendering error

- alma/lib/Helpers/ModuleHelper.php
- alma/tests/Unit/Services/CartSaveServiceTest.php
> QA test before release v1560

- alma/lib/Services/InsuranceApiService.php
[Linear task](https://linear.app/almapay/issue/ECOM-1754/hotfix-fatal-error-when-insurance-in-400)
Buy an insurance
> HOTFIX Define product helper

- alma/controllers/front/insurance.php
- alma/controllers/hook/ActionCartSaveHookController.php
- alma/controllers/hook/DisplayCartExtraProductActionsHookController.php
- alma/lib/Helpers/InsuranceHelper.php
- alma/views/js/alma-cart-insurance.js
- alma/views/js/alma-product-insurance.js
[Linear task](https://linear.app/almapay/issue/ECOM-1772/[🧩-ps]-get-and-use-the-insurance-quantity)
send quantity to widget and get insurance quantity to buy
> [cart-item] send quantity to widget and get insurance quantity to buy

- alma/alma.php
- alma/controllers/hook/GetContentHookController.php
- alma/views/css/admin/almaPage.css
[Linear task](https://linear.app/almapay/issue/ECOM-1794/[fix]-ps-account-display)
We display the getContent if has or suggest psAccount
Install our module and see if PS Account is displayed in our module before the configuration
Need the module Ps account to work
> [ps-account] Fix display ps account

- scripts/build/Dockerfile
> fix: builder module

- alma/controllers/admin/AdminAlmaInsuranceConfiguration.php
- alma/controllers/admin/AdminAlmaInsuranceOrdersDetails.php
- alma/controllers/hook/DisplayProductActionsHookController.php
- alma/lib/Builders/Admin/InsuranceHelperBuilder.php
- alma/lib/Helpers/Admin/AdminInsuranceHelper.php
- alma/lib/Helpers/ApiHelper.php
- alma/lib/Traits/BuilderTrait.php
- alma/tests/Unit/Builders/Admin/InsuranceHelperBuilderTest.php
- alma/tests/Unit/Builders/Helpers/ApiHelperBuilderTest.php
[Linear task](https://linear.app/almapay/issue/ECOM-1796/[🧩-ps]-fix-module-for-php-56)
We renamed the Class InsuranceHelper in Admin to AdminInsuranceHelper for compatibility with PHP 5.6
We need to test in the merchant infra because we don't reproduce in local
> Fix compatibility PHP 5.6

- alma/controllers/front/insurance.php
- alma/controllers/hook/ActionCartSaveHookController.php
- alma/controllers/hook/DisplayAdminOrderTopHookController.php
- alma/controllers/hook/DisplayCartExtraProductActionsHookController.php
- alma/lib/Factories/CombinationFactory.php
- alma/lib/Factories/LinkFactory.php
- alma/lib/Factories/ProductFactory.php
- alma/lib/Helpers/ToolsHelper.php
- alma/lib/Repositories/AlmaInsuranceProductRepository.php
- alma/lib/Services/InsuranceProductService.php
- alma/lib/Traits/BuilderTrait.php
- alma/tests/Unit/Helper/ToolsHelperTest.php
- alma/tests/Unit/Services/InsuranceProductServiceTest.php
- alma/views/css/alma-insurance.css
- alma/views/js/alma-cart-insurance.js
- alma/views/templates/hook/_partials/itemCartInsuranceProduct.tpl
- alma/views/templates/hook/_partials/widgetAddInsuranceProducts.tpl
- alma/views/templates/hook/displayCartExtraProductActions.tpl
- scripts/build/Dockerfile
[Linear task](https://linear.app/almapay/issue/ECOM-1802/[🧩-ps]-new-design-for-insurance-widget-in-the-cart-page)
[Linear task](https://linear.app/almapay/issue/ECOM-1803/[🧩-ps]-add-all-the-same-insurance-of-product-in-the-cart-page)
https://www.notion.so/almapay/Improve-cart-item-level-selector-design-2e5e7e1523fc401fb246b67df982b170
> [cart-item] feat: new design cart item + add all same insurance on cart page

- alma/views/css/alma-insurance.css
[Linear task](https://linear.app/almapay/issue/ECOM-1816/[💅ps]-delete-icon-should-be-black)
Inherit color for trash button in cart item insurance (black color in default theme)
See the delete button of cart item for insurance
> feat: Delete icon should be black

- .github/workflows/release-pull-request.yml
> [DEVX] Fix release drafter branch

- alma/views/js/alma-cart-insurance.js
[Linear task](https://linear.app/almapay/issue/ECOM-1859/[🧩-ps]-fix-script-to-add-insurance-for-cart-page-ipln)
removeLoaderDot function is called for add to insurance from cart
We remove the eventListener after the first one
Need to test at the merchant
> fix: add insurance from cart page with multiple execution

- alma/config/admin/services.yml
[Linear task](https://linear.app/almapay/issue/ECOM-1869/[🧩-ps]-issue-ps-account-with-ps-817)
Make service public for PS Account lib
Up an infra in Ps 8 with alma module
> fix: Issue PS Account with PS 8.1.7

- Taskfile.yml
Add info in `task release` to help ECOM integrations team with the Marketplace publication step
* Update `task release` and `task hotfix`
* Add `task release:help` and `task hotfix:help` to be able to get these info at any time.
> [DEVX] Add info for Marketplace publication in task release

- alma/lib/Factories/LinkFactory.php
- alma/lib/Services/InsuranceProductService.php
- alma/tests/Unit/Services/InsuranceProductServiceTest.php
[Linear task](https://linear.app/almapay/issue/ECOM-1884/[🧩-ps]-issue-declaration-linkfactory)
Fix Declaration about LinkFactory
Display the items in cart page
> fix: Declaration LinkFactory

- alma/views/js/alma-insurance.js
- alma/views/js/alma-product-insurance.js
[Linear task](https://linear.app/almapay/issue/ECOM-1885/[🧩-ps]-issue-add-to-cart-button-with-insurance-on-display-mobile-ipln)
On display mobile check input for mini cart
> fix: Issue with insurance on mobile display

- alma/alma.php
- alma/lib/Helpers/HookHelper.php
[Linear task](https://linear.app/almapay/issue/ECOM-1887/[🧩-ps]-remove-insurance-product-when-removing-the-product-with)
Update hooks to handle the removing insurance product when removing a product
Add an insurance product and remove the product of this insurance
> [compatibility] feat: Remove insurance product when removing the product with insurance

- alma/controllers/hook/DisplayCartExtraProductActionsHookController.php
- alma/controllers/hook/DisplayProductActionsHookController.php
- alma/lib/Services/InsuranceApiService.php
[Linear task](https://linear.app/almapay/issue/ECOM-1888/[🧩-ps]-send-a-sessionid-to-the-insurance-api)
Replace `$this->context->session->getId()` to `$this->context->cookie->checksum`
Subscribe an insurance
> [compatibility] feat: Send a sessionId to the Insurance API

- alma/lib/Helpers/HookHelper.php
[Linear task](https://linear.app/almapay/issue/ECOM-1890/[🧩-ps]-add-notification-in-the-order-page-if-the-order-has-an)
We added the notification insurance in the hook displayInvoice
Subscribe an insurance and see the order page on the dashboard
> [compatibility] feat: Add notification in the order page if the order has an insurance

- alma/lib/Model/InsuranceProduct.php
[Linear task](https://linear.app/almapay/issue/ECOM-1891/[🧩-ps]-create-the-subscription-when-the-order-payment-is-validated)
We override the update native function with the code of last prestashop version because the native function for old version use the function get_class et our namespace can use this function
Subscribe an insurance
> [compatibility] feat: Create the subscription when the order payment is validated

- alma/controllers/hook/DisplayCartExtraProductActionsHookController.php
- alma/exceptions/AlmaCartItemFactoryException.php
- alma/lib/Builders/Repositories/InsuranceProductRepositoryBuilder.php
- alma/lib/Builders/Services/InsuranceProductServiceBuilder.php
- alma/lib/Factories/AlmaCartItemFactory.php
- alma/lib/Factories/CombinationFactory.php
- alma/lib/Factories/LinkFactory.php
- alma/lib/Factories/ProductFactory.php
- alma/lib/Helpers/PriceHelper.php
- alma/lib/Helpers/ToolsHelper.php
- alma/lib/Model/AlmaCartItemModel.php
- alma/lib/Model/InsuranceProduct.php
- alma/lib/Repositories/AlmaInsuranceProductRepository.php
- alma/lib/Services/AttributeProductService.php
- alma/lib/Services/CombinationProductAttributeService.php
- alma/lib/Services/InsuranceProductService.php
- alma/lib/Services/InsuranceSubscriptionService.php
- alma/phpunit.ci.xml
- alma/tests/Unit/Builders/InsuranceHelperBuilderTest.php
- alma/tests/Unit/Builders/Repositories/InsuranceProductRepositoryBuilderTest.php
- alma/tests/Unit/Factories/AlmaCartItemFactoryTest.php
- alma/tests/Unit/Model/AlmaCartItemModelTest.php
- alma/tests/Unit/Services/InsuranceProductServiceTest.php
- alma/upgrade/upgrade-4.2.0.php
- alma/views/css/alma-insurance.css
- alma/views/js/alma-product-insurance.js
- alma/views/templates/hook/_partials/itemCartInsuranceProduct.tpl
- alma/views/templates/hook/_partials/widgetAddInsuranceProducts.tpl
- alma/views/templates/hook/displayCartExtraProductActions.tpl
- alma/views/templates/hook/notificationError.tpl
[Linear task](https://linear.app/almapay/issue/ECOM-1889/[🧩-ps]-add-insurance-product-with-an-eligible-product)
[Linear task](https://linear.app/almapay/issue/ECOM-1893/[🧩-ps]-display-insurance-in-the-cart-item)
Create an object CartItem to handle the compatibility with all Prestashop version
Some fix in Template and JS asset to add insurance product
Add an insurance produit with an eligible product in Cart on Prestashop 1.7.0.6
> [compatibility] feat: Add insurance product with an eligible product

- alma/alma.php
[Linear task](https://linear.app/almapay/issue/ECOM-1940/[🧩-ps]-fix-compatibility-ps-16-during-installing-module)
We remove use called in the alma.php Because isn't compatible with PS 1.6
Install the module in PS 1.6
> fix: compatibility PS 1.6 during installing module

- alma/views/js/alma-product-insurance.js
- alma/views/templates/hook/_partials/itemCartInsuranceProduct.tpl
[Linear task](https://linear.app/almapay/issue/ECOM-1907/[🧩-ps]-fix-to-add-quantity-insurance-in-the-product-page-item)
We add row in cart item to fix display
If there isn't event when the quantity change, we get the quantity in the input to send to the value in the widget
Issue identify in the merchant website
> Fix: add quantity insurance in the product and display cart item

- alma/views/templates/hook/displayCartExtraProductActions.tpl
> fix: remove dump

- .github/renovate.json
* Fix `dockerfile` manager.
* Disable major composer updates (pr is always closed)
> Fix renovate configuration and disable major composer updates

- alma/lib/Services/OrderService.php
[Linear task](https://linear.app/almapay/issue/ECOM-1909/eco-motos-pieces-error-500)
We add a verification if order hasn't status we don't send the status to order endpoint
Identify by merchant
> fix: change order status error

- alma/views/js/alma-product-insurance.js
[Linear task](https://linear.app/almapay/issue/ECOM-1949/[-ps]-fix-openmodal-in-first-load-product-page-ipln)
We reload the product page in the first time for product with insurance
Issue identify in merchant store
> fix: openmodal insurance in the first load product page

- alma/config/admin/services.yml
[Linear task](https://linear.app/almapay/issue/ECOM-1959/[-ps]-fix-install-module-with-ps-account-from-ps17-to-ps-8)
We remove the service _default in the services.yaml
Install our module in PS 1.7.0.6, PS 1.7.8.7 and PS 8.1.7
> fix: install module with ps_account from ps17 to ps8

- alma/tests/Unit/Model/CartDataTest.php
> fix: unit-test

- alma/controllers/front/ipn.php
- alma/controllers/front/validation.php
- alma/lib/Validators/PaymentValidation.php
- alma/tests/Unit/Validators/PaymentValidationTest.php
[Linear task](https://linear.app/almapay/issue/ECOM-2102/[-ps]-fix-paymentvalidation-in-validation-controller-since-hmac)
Since the HMAC feature, we created a builder paymentValidation. The builder was loaded in the ipn controller but not in the validation controller.
We fix the validation controller by adding the builder and the injection of moduleFactory in the paymentValidator
Make an order and pay with Alma. You will redirect to the thank page correctly
> fix: paymentValidation in validation controller since HMAC

- alma/views/css/alma-insurance.css
[Linear task](https://linear.app/almapay/issue/ECOM-2113/[-ps]-fix-display-widget-ps-17)
We add a selector to hide the productDetails in PS 1.7.0.6
Display the widget insurance on product in PS 1.7.0.6
[Env Test QA](https://qa-release-440-prestashop-1-7-0-6.integrations.getalma.eu/)
> fix: display widget on PS 1.7.0.6

- alma/lib/Forms/InpageAdminFormBuilder.php
- alma/translations/en.php
- alma/translations/fr.php
[Linear task](https://linear.app/almapay/issue/ECOM-2153/[ps]-update-wording-for-in-page-advanced-feature)
We change the wording of in-page configuration
Display the configuration page and see the wording of in-page feature
> feat: Update wording for In-Page advanced feature

- alma/lib/Helpers/PaymentOptionHelper.php
[Linear task](https://linear.app/almapay/issue/ECOM-2263/[-ps]-fix-custom-description-for-payment-button-credit)
We change the constante to get the right field of description payment button for credit
Change the description of payment button credit and check in front the custom description
> fix: Custom Description for payment button credit

- alma/lib/Helpers/ThemeHelper.php
> Fix theme helper

- alma/alma.php
- alma/controllers/hook/GetContentHookController.php
- alma/lib/Forms/ApiAdminFormBuilder.php
- alma/lib/Helpers/ApiHelper.php
- alma/lib/Model/AlmaApiKeyModel.php
- alma/lib/Proxy/ConfigurationProxy.php
- alma/lib/Proxy/ModuleProxy.php
- alma/lib/Services/AdminFormBuilderService.php
- alma/lib/Services/ConfigFormService.php
- alma/lib/Services/PsAccountService.php
- alma/lib/Services/PsAccountsService.php
- alma/tests/Unit/Forms/ApiAdminFormBuilderTest.php
- alma/tests/Unit/Services/AdminFormBuilderServiceTest.php
- alma/views/templates/hook/_partials/notificationFormConfiguration.tpl
- alma/views/templates/hook/_partials/notificationPsAccount.tpl
- alma/views/templates/hook/configurationContent.tpl
[Linear task](https://linear.app/almapay/issue/ECOM-2274/[-ps-refacto]-display-ps-account-in-the-config-form)
Add PS Account
[Doc to test PS Account](https://www.notion.so/almapay/ECOM-Project-s-center-10d18a22216a80279180fe703407fb8d?p=16218a22216a8068844ffedb8d7cf483&pm=s)
> feat: Add ps account

- alma/alma.php
Fix migration after refacto
Remove injection in construct alma.php for migration from old version
> fix: migration after refacto

- alma/lib/Model/PaymentData.php
[Linear task](https://linear.app/almapay/issue/ECOM-2369/3as-racing-logs-in-the-bascket)
We moved the getCustomer after the return for widget eligibility if `ALMA_CART_WDGT_NOT_ELGBL` is set to false.
Because we use the same eligibility function but at this moment we may not know the customer, that's why we don't need to get the customer before, but only to create the payment data.
BackOffice : 
Disable the option `Display even if the cart is not eligible` for widget cart
Enable the log mode
Front Office :
Logout to any customer account
Create a cart with one or more product
See the log without any error about `[Alma] Error loading Customer {idCustomer} from Cart {idCart}`
> fix: Avoid error about get customer for eligibility of cart widget

- alma/controllers/hook/FrontHeaderHookController.php
[Linear task](https://linear.app/almapay/issue/ECOM-2395/[-ps]-fix-update-html-element-in-frontheaderhookcontroller-for-better)
[Issue link](https://github.com/alma/alma-installments-prestashop/issues/635)
The current implementation uses a <div> element within the HTML <head> section to store Alma payment configuration data. This creates semantic HTML issues as <div> elements should not be placed in the <head> section. This incorrect placement causes Smarty template engine to attempt corrections, which breaks the data binding on the <body> element, ultimately causing payment methods and order validation to malfunction.
- Replaced the `<div>` element with a `<meta>` element in the `almaInPageHeader()` method
- Maintained the same data structure and attributes while using a more …
> fix: Update HTML element in FrontHeaderHookController for better semantic

- alma/views/templates/hook/_partials/displayPayment_pnx.tpl
Files removed in a previous PR, no identify how this file was removed. This PR is for rollback this template file for PS 1.6
Rollback file removed
> fix: Rollback file removed for PS 1.6

- alma/lib/Hooks/HookController.php
[Linear task](https://linear.app/almapay/issue/ECOM-2397/merchant-getting-recurring-errors-on-prestashop)
> fix: controller unknown for marketplace tool

- alma/controllers/front/cmsdataexport.php
- alma/tests/Unit/Controllers/Front/CmsDataExportTest.php
[Linear task](https://linear.app/almapay/issue/ECOM-2491/[ps]-add-error-code-403-for-invalid-signature-in-gather-cms-data)
Add ajaxRenderAndExit in checksignature 
> Add error code 403 for invalid signature in gather cms data

- alma/controllers/hook/ActionCartSaveHookController.php
[Linear task](https://linear.app/almapay/issue/ECOM-2517/[ps]-fix-issue-with-missing-objectcart-id-during-checkout-process)
We added a verification cart is object before use BusinessDataService to avoid error during checkout process
Mount an old Prestashop version < 1.7.7.0
Make a new checkout process until payment
> fix: Issue checkout process with old Prestashop version

- alma/views/js/alma-inpage.js
[Linear task](https://linear.app/almapay/issue/ECOM-2539/inpage-weird-calls-to-return-urls-payment-id-is-undefined-or-absent)
Asked by the Purchase Experience Team, we check the payment payment_id exist before startPayment with inPage
> feat: Weird calls to /return-urls. Payment id is undefined or absent

- README.md
[Linear task](https://linear.app/almapay/issue/ECOM-2543/[-ps]-update-readme-github-with-version-compatibility)
Update README for requirement and compatibility
No test
> feat: update README for compatibility version

- alma/lib/Helpers/ConstantsHelper.php
Update widget version
[Linear task](https://linear.app/almapay/issue/ECOM-2288/[ps]-implement-new-widget-version)
change version reference
launch prestashop and check version in sources
> feat: update widget version to 4.x.x

- alma/lib/Forms/InpageAdminFormBuilder.php
- alma/translations/de.php
- alma/translations/en.php
- alma/translations/es.php
- alma/translations/fr.php
- alma/translations/it.php
- alma/translations/nl.php
- alma/translations/pt.php
[Linear task](https://linear.app/almapay/issue/ECOM-2617/[-ps]-re-wording-in-page-back-office-field)
Re-wording the description for the field Activate In-Page and translate it
> feat: Re-wording in page back office field

- alma/composer.json
- alma/lib/Helpers/CmsDataHelper.php
- alma/lib/Model/AlmaModuleModel.php
- alma/tests/Unit/Controllers/Front/CmsDataExportTest.php
- alma/tests/Unit/Helper/CmsDataHelperTest.php
- alma/tests/Unit/Model/AlmaModuleModelTest.php
[Linear task](https://linear.app/almapay/issue/ECOM-3351/add-payment-method-list-in-prestashop-for-gather-cms-data)
Add payment methods list to cms features
> feat: add payment methods list in gather CMS data
